// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RCRS.proto

package kernel;

public interface AgentProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:simpleRCRS.AgentProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 AgentType = 1;</code>
   * @return The agentType.
   */
  int getAgentType();

  /**
   * <code>int32 AgentID = 2;</code>
   * @return The agentID.
   */
  int getAgentID();
}
