// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RCRS.proto

package kernel;

/**
 * Protobuf type {@code simpleRCRS.AgentProto}
 */
public  final class AgentProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:simpleRCRS.AgentProto)
    AgentProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AgentProto.newBuilder() to construct.
  private AgentProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AgentProto() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AgentProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AgentProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            agentType_ = input.readInt32();
            break;
          }
          case 16: {

            agentID_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return kernel.RCRSProto.internal_static_simpleRCRS_AgentProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return kernel.RCRSProto.internal_static_simpleRCRS_AgentProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            kernel.AgentProto.class, kernel.AgentProto.Builder.class);
  }

  public static final int AGENTTYPE_FIELD_NUMBER = 1;
  private int agentType_;
  /**
   * <code>int32 AgentType = 1;</code>
   * @return The agentType.
   */
  public int getAgentType() {
    return agentType_;
  }

  public static final int AGENTID_FIELD_NUMBER = 2;
  private int agentID_;
  /**
   * <code>int32 AgentID = 2;</code>
   * @return The agentID.
   */
  public int getAgentID() {
    return agentID_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (agentType_ != 0) {
      output.writeInt32(1, agentType_);
    }
    if (agentID_ != 0) {
      output.writeInt32(2, agentID_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (agentType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, agentType_);
    }
    if (agentID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, agentID_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof kernel.AgentProto)) {
      return super.equals(obj);
    }
    kernel.AgentProto other = (kernel.AgentProto) obj;

    if (getAgentType()
        != other.getAgentType()) return false;
    if (getAgentID()
        != other.getAgentID()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AGENTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getAgentType();
    hash = (37 * hash) + AGENTID_FIELD_NUMBER;
    hash = (53 * hash) + getAgentID();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static kernel.AgentProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kernel.AgentProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kernel.AgentProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kernel.AgentProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kernel.AgentProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kernel.AgentProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kernel.AgentProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kernel.AgentProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static kernel.AgentProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static kernel.AgentProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static kernel.AgentProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kernel.AgentProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(kernel.AgentProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code simpleRCRS.AgentProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:simpleRCRS.AgentProto)
      kernel.AgentProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kernel.RCRSProto.internal_static_simpleRCRS_AgentProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kernel.RCRSProto.internal_static_simpleRCRS_AgentProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kernel.AgentProto.class, kernel.AgentProto.Builder.class);
    }

    // Construct using kernel.AgentProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      agentType_ = 0;

      agentID_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return kernel.RCRSProto.internal_static_simpleRCRS_AgentProto_descriptor;
    }

    @java.lang.Override
    public kernel.AgentProto getDefaultInstanceForType() {
      return kernel.AgentProto.getDefaultInstance();
    }

    @java.lang.Override
    public kernel.AgentProto build() {
      kernel.AgentProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public kernel.AgentProto buildPartial() {
      kernel.AgentProto result = new kernel.AgentProto(this);
      result.agentType_ = agentType_;
      result.agentID_ = agentID_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof kernel.AgentProto) {
        return mergeFrom((kernel.AgentProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(kernel.AgentProto other) {
      if (other == kernel.AgentProto.getDefaultInstance()) return this;
      if (other.getAgentType() != 0) {
        setAgentType(other.getAgentType());
      }
      if (other.getAgentID() != 0) {
        setAgentID(other.getAgentID());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      kernel.AgentProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (kernel.AgentProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int agentType_ ;
    /**
     * <code>int32 AgentType = 1;</code>
     * @return The agentType.
     */
    public int getAgentType() {
      return agentType_;
    }
    /**
     * <code>int32 AgentType = 1;</code>
     * @param value The agentType to set.
     * @return This builder for chaining.
     */
    public Builder setAgentType(int value) {
      
      agentType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 AgentType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAgentType() {
      
      agentType_ = 0;
      onChanged();
      return this;
    }

    private int agentID_ ;
    /**
     * <code>int32 AgentID = 2;</code>
     * @return The agentID.
     */
    public int getAgentID() {
      return agentID_;
    }
    /**
     * <code>int32 AgentID = 2;</code>
     * @param value The agentID to set.
     * @return This builder for chaining.
     */
    public Builder setAgentID(int value) {
      
      agentID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 AgentID = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAgentID() {
      
      agentID_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:simpleRCRS.AgentProto)
  }

  // @@protoc_insertion_point(class_scope:simpleRCRS.AgentProto)
  private static final kernel.AgentProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new kernel.AgentProto();
  }

  public static kernel.AgentProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AgentProto>
      PARSER = new com.google.protobuf.AbstractParser<AgentProto>() {
    @java.lang.Override
    public AgentProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AgentProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AgentProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AgentProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public kernel.AgentProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

