// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RCRS.proto

package kernel;

/**
 * Protobuf type {@code simpleRCRS.AreaProto}
 */
public  final class AreaProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:simpleRCRS.AreaProto)
    AreaProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AreaProto.newBuilder() to construct.
  private AreaProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AreaProto() {
    uRN_ = "";
    edges_ = java.util.Collections.emptyList();
    blockades_ = emptyIntList();
    apexList_ = emptyIntList();
    neighbours_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AreaProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AreaProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            uRN_ = s;
            break;
          }
          case 16: {

            iD_ = input.readInt32();
            break;
          }
          case 24: {

            x_ = input.readInt32();
            break;
          }
          case 32: {

            y_ = input.readInt32();
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              edges_ = new java.util.ArrayList<kernel.EdgeProto>();
              mutable_bitField0_ |= 0x00000001;
            }
            edges_.add(
                input.readMessage(kernel.EdgeProto.parser(), extensionRegistry));
            break;
          }
          case 48: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              blockades_ = newIntList();
              mutable_bitField0_ |= 0x00000002;
            }
            blockades_.addInt(input.readInt32());
            break;
          }
          case 50: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
              blockades_ = newIntList();
              mutable_bitField0_ |= 0x00000002;
            }
            while (input.getBytesUntilLimit() > 0) {
              blockades_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 56: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              apexList_ = newIntList();
              mutable_bitField0_ |= 0x00000004;
            }
            apexList_.addInt(input.readInt32());
            break;
          }
          case 58: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000004) != 0) && input.getBytesUntilLimit() > 0) {
              apexList_ = newIntList();
              mutable_bitField0_ |= 0x00000004;
            }
            while (input.getBytesUntilLimit() > 0) {
              apexList_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 64: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              neighbours_ = newIntList();
              mutable_bitField0_ |= 0x00000008;
            }
            neighbours_.addInt(input.readInt32());
            break;
          }
          case 66: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000008) != 0) && input.getBytesUntilLimit() > 0) {
              neighbours_ = newIntList();
              mutable_bitField0_ |= 0x00000008;
            }
            while (input.getBytesUntilLimit() > 0) {
              neighbours_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 72: {

            floors_ = input.readInt32();
            break;
          }
          case 80: {

            ignition_ = input.readBool();
            break;
          }
          case 88: {

            fieryness_ = input.readInt32();
            break;
          }
          case 96: {

            brokenness_ = input.readInt32();
            break;
          }
          case 104: {

            buildingCode_ = input.readInt32();
            break;
          }
          case 112: {

            buildingAttributes_ = input.readInt32();
            break;
          }
          case 120: {

            groundArea_ = input.readInt32();
            break;
          }
          case 128: {

            totalArea_ = input.readInt32();
            break;
          }
          case 136: {

            temperature_ = input.readInt32();
            break;
          }
          case 144: {

            importance_ = input.readInt32();
            break;
          }
          case 152: {

            isOnFire_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        edges_ = java.util.Collections.unmodifiableList(edges_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        blockades_.makeImmutable(); // C
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        apexList_.makeImmutable(); // C
      }
      if (((mutable_bitField0_ & 0x00000008) != 0)) {
        neighbours_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return kernel.RCRSProto.internal_static_simpleRCRS_AreaProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return kernel.RCRSProto.internal_static_simpleRCRS_AreaProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            kernel.AreaProto.class, kernel.AreaProto.Builder.class);
  }

  public static final int URN_FIELD_NUMBER = 1;
  private volatile java.lang.Object uRN_;
  /**
   * <code>string uRN = 1;</code>
   * @return The uRN.
   */
  public java.lang.String getURN() {
    java.lang.Object ref = uRN_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uRN_ = s;
      return s;
    }
  }
  /**
   * <code>string uRN = 1;</code>
   * @return The bytes for uRN.
   */
  public com.google.protobuf.ByteString
      getURNBytes() {
    java.lang.Object ref = uRN_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uRN_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 2;
  private int iD_;
  /**
   * <code>int32 iD = 2;</code>
   * @return The iD.
   */
  public int getID() {
    return iD_;
  }

  public static final int X_FIELD_NUMBER = 3;
  private int x_;
  /**
   * <code>int32 x = 3;</code>
   * @return The x.
   */
  public int getX() {
    return x_;
  }

  public static final int Y_FIELD_NUMBER = 4;
  private int y_;
  /**
   * <code>int32 y = 4;</code>
   * @return The y.
   */
  public int getY() {
    return y_;
  }

  public static final int EDGES_FIELD_NUMBER = 5;
  private java.util.List<kernel.EdgeProto> edges_;
  /**
   * <code>repeated .simpleRCRS.EdgeProto edges = 5;</code>
   */
  public java.util.List<kernel.EdgeProto> getEdgesList() {
    return edges_;
  }
  /**
   * <code>repeated .simpleRCRS.EdgeProto edges = 5;</code>
   */
  public java.util.List<? extends kernel.EdgeProtoOrBuilder> 
      getEdgesOrBuilderList() {
    return edges_;
  }
  /**
   * <code>repeated .simpleRCRS.EdgeProto edges = 5;</code>
   */
  public int getEdgesCount() {
    return edges_.size();
  }
  /**
   * <code>repeated .simpleRCRS.EdgeProto edges = 5;</code>
   */
  public kernel.EdgeProto getEdges(int index) {
    return edges_.get(index);
  }
  /**
   * <code>repeated .simpleRCRS.EdgeProto edges = 5;</code>
   */
  public kernel.EdgeProtoOrBuilder getEdgesOrBuilder(
      int index) {
    return edges_.get(index);
  }

  public static final int BLOCKADES_FIELD_NUMBER = 6;
  private com.google.protobuf.Internal.IntList blockades_;
  /**
   * <code>repeated int32 blockades = 6;</code>
   * @return A list containing the blockades.
   */
  public java.util.List<java.lang.Integer>
      getBlockadesList() {
    return blockades_;
  }
  /**
   * <code>repeated int32 blockades = 6;</code>
   * @return The count of blockades.
   */
  public int getBlockadesCount() {
    return blockades_.size();
  }
  /**
   * <code>repeated int32 blockades = 6;</code>
   * @param index The index of the element to return.
   * @return The blockades at the given index.
   */
  public int getBlockades(int index) {
    return blockades_.getInt(index);
  }
  private int blockadesMemoizedSerializedSize = -1;

  public static final int APEXLIST_FIELD_NUMBER = 7;
  private com.google.protobuf.Internal.IntList apexList_;
  /**
   * <code>repeated int32 apexList = 7;</code>
   * @return A list containing the apexList.
   */
  public java.util.List<java.lang.Integer>
      getApexListList() {
    return apexList_;
  }
  /**
   * <code>repeated int32 apexList = 7;</code>
   * @return The count of apexList.
   */
  public int getApexListCount() {
    return apexList_.size();
  }
  /**
   * <code>repeated int32 apexList = 7;</code>
   * @param index The index of the element to return.
   * @return The apexList at the given index.
   */
  public int getApexList(int index) {
    return apexList_.getInt(index);
  }
  private int apexListMemoizedSerializedSize = -1;

  public static final int NEIGHBOURS_FIELD_NUMBER = 8;
  private com.google.protobuf.Internal.IntList neighbours_;
  /**
   * <code>repeated int32 neighbours = 8;</code>
   * @return A list containing the neighbours.
   */
  public java.util.List<java.lang.Integer>
      getNeighboursList() {
    return neighbours_;
  }
  /**
   * <code>repeated int32 neighbours = 8;</code>
   * @return The count of neighbours.
   */
  public int getNeighboursCount() {
    return neighbours_.size();
  }
  /**
   * <code>repeated int32 neighbours = 8;</code>
   * @param index The index of the element to return.
   * @return The neighbours at the given index.
   */
  public int getNeighbours(int index) {
    return neighbours_.getInt(index);
  }
  private int neighboursMemoizedSerializedSize = -1;

  public static final int FLOORS_FIELD_NUMBER = 9;
  private int floors_;
  /**
   * <pre>
   *&#47;// below for buildings
   * </pre>
   *
   * <code>int32 floors = 9;</code>
   * @return The floors.
   */
  public int getFloors() {
    return floors_;
  }

  public static final int IGNITION_FIELD_NUMBER = 10;
  private boolean ignition_;
  /**
   * <code>bool ignition = 10;</code>
   * @return The ignition.
   */
  public boolean getIgnition() {
    return ignition_;
  }

  public static final int FIERYNESS_FIELD_NUMBER = 11;
  private int fieryness_;
  /**
   * <code>int32 fieryness = 11;</code>
   * @return The fieryness.
   */
  public int getFieryness() {
    return fieryness_;
  }

  public static final int BROKENNESS_FIELD_NUMBER = 12;
  private int brokenness_;
  /**
   * <code>int32 brokenness = 12;</code>
   * @return The brokenness.
   */
  public int getBrokenness() {
    return brokenness_;
  }

  public static final int BUILDINGCODE_FIELD_NUMBER = 13;
  private int buildingCode_;
  /**
   * <code>int32 buildingCode = 13;</code>
   * @return The buildingCode.
   */
  public int getBuildingCode() {
    return buildingCode_;
  }

  public static final int BUILDINGATTRIBUTES_FIELD_NUMBER = 14;
  private int buildingAttributes_;
  /**
   * <code>int32 buildingAttributes = 14;</code>
   * @return The buildingAttributes.
   */
  public int getBuildingAttributes() {
    return buildingAttributes_;
  }

  public static final int GROUNDAREA_FIELD_NUMBER = 15;
  private int groundArea_;
  /**
   * <code>int32 groundArea = 15;</code>
   * @return The groundArea.
   */
  public int getGroundArea() {
    return groundArea_;
  }

  public static final int TOTALAREA_FIELD_NUMBER = 16;
  private int totalArea_;
  /**
   * <code>int32 totalArea = 16;</code>
   * @return The totalArea.
   */
  public int getTotalArea() {
    return totalArea_;
  }

  public static final int TEMPERATURE_FIELD_NUMBER = 17;
  private int temperature_;
  /**
   * <code>int32 temperature = 17;</code>
   * @return The temperature.
   */
  public int getTemperature() {
    return temperature_;
  }

  public static final int IMPORTANCE_FIELD_NUMBER = 18;
  private int importance_;
  /**
   * <code>int32 importance = 18;</code>
   * @return The importance.
   */
  public int getImportance() {
    return importance_;
  }

  public static final int ISONFIRE_FIELD_NUMBER = 19;
  private boolean isOnFire_;
  /**
   * <code>bool isOnFire = 19;</code>
   * @return The isOnFire.
   */
  public boolean getIsOnFire() {
    return isOnFire_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!getURNBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uRN_);
    }
    if (iD_ != 0) {
      output.writeInt32(2, iD_);
    }
    if (x_ != 0) {
      output.writeInt32(3, x_);
    }
    if (y_ != 0) {
      output.writeInt32(4, y_);
    }
    for (int i = 0; i < edges_.size(); i++) {
      output.writeMessage(5, edges_.get(i));
    }
    if (getBlockadesList().size() > 0) {
      output.writeUInt32NoTag(50);
      output.writeUInt32NoTag(blockadesMemoizedSerializedSize);
    }
    for (int i = 0; i < blockades_.size(); i++) {
      output.writeInt32NoTag(blockades_.getInt(i));
    }
    if (getApexListList().size() > 0) {
      output.writeUInt32NoTag(58);
      output.writeUInt32NoTag(apexListMemoizedSerializedSize);
    }
    for (int i = 0; i < apexList_.size(); i++) {
      output.writeInt32NoTag(apexList_.getInt(i));
    }
    if (getNeighboursList().size() > 0) {
      output.writeUInt32NoTag(66);
      output.writeUInt32NoTag(neighboursMemoizedSerializedSize);
    }
    for (int i = 0; i < neighbours_.size(); i++) {
      output.writeInt32NoTag(neighbours_.getInt(i));
    }
    if (floors_ != 0) {
      output.writeInt32(9, floors_);
    }
    if (ignition_ != false) {
      output.writeBool(10, ignition_);
    }
    if (fieryness_ != 0) {
      output.writeInt32(11, fieryness_);
    }
    if (brokenness_ != 0) {
      output.writeInt32(12, brokenness_);
    }
    if (buildingCode_ != 0) {
      output.writeInt32(13, buildingCode_);
    }
    if (buildingAttributes_ != 0) {
      output.writeInt32(14, buildingAttributes_);
    }
    if (groundArea_ != 0) {
      output.writeInt32(15, groundArea_);
    }
    if (totalArea_ != 0) {
      output.writeInt32(16, totalArea_);
    }
    if (temperature_ != 0) {
      output.writeInt32(17, temperature_);
    }
    if (importance_ != 0) {
      output.writeInt32(18, importance_);
    }
    if (isOnFire_ != false) {
      output.writeBool(19, isOnFire_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getURNBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uRN_);
    }
    if (iD_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, iD_);
    }
    if (x_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, x_);
    }
    if (y_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, y_);
    }
    for (int i = 0; i < edges_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, edges_.get(i));
    }
    {
      int dataSize = 0;
      for (int i = 0; i < blockades_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(blockades_.getInt(i));
      }
      size += dataSize;
      if (!getBlockadesList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      blockadesMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      for (int i = 0; i < apexList_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(apexList_.getInt(i));
      }
      size += dataSize;
      if (!getApexListList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      apexListMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      for (int i = 0; i < neighbours_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(neighbours_.getInt(i));
      }
      size += dataSize;
      if (!getNeighboursList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      neighboursMemoizedSerializedSize = dataSize;
    }
    if (floors_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, floors_);
    }
    if (ignition_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, ignition_);
    }
    if (fieryness_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, fieryness_);
    }
    if (brokenness_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, brokenness_);
    }
    if (buildingCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(13, buildingCode_);
    }
    if (buildingAttributes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(14, buildingAttributes_);
    }
    if (groundArea_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(15, groundArea_);
    }
    if (totalArea_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(16, totalArea_);
    }
    if (temperature_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(17, temperature_);
    }
    if (importance_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(18, importance_);
    }
    if (isOnFire_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(19, isOnFire_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof kernel.AreaProto)) {
      return super.equals(obj);
    }
    kernel.AreaProto other = (kernel.AreaProto) obj;

    if (!getURN()
        .equals(other.getURN())) return false;
    if (getID()
        != other.getID()) return false;
    if (getX()
        != other.getX()) return false;
    if (getY()
        != other.getY()) return false;
    if (!getEdgesList()
        .equals(other.getEdgesList())) return false;
    if (!getBlockadesList()
        .equals(other.getBlockadesList())) return false;
    if (!getApexListList()
        .equals(other.getApexListList())) return false;
    if (!getNeighboursList()
        .equals(other.getNeighboursList())) return false;
    if (getFloors()
        != other.getFloors()) return false;
    if (getIgnition()
        != other.getIgnition()) return false;
    if (getFieryness()
        != other.getFieryness()) return false;
    if (getBrokenness()
        != other.getBrokenness()) return false;
    if (getBuildingCode()
        != other.getBuildingCode()) return false;
    if (getBuildingAttributes()
        != other.getBuildingAttributes()) return false;
    if (getGroundArea()
        != other.getGroundArea()) return false;
    if (getTotalArea()
        != other.getTotalArea()) return false;
    if (getTemperature()
        != other.getTemperature()) return false;
    if (getImportance()
        != other.getImportance()) return false;
    if (getIsOnFire()
        != other.getIsOnFire()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + URN_FIELD_NUMBER;
    hash = (53 * hash) + getURN().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getID();
    hash = (37 * hash) + X_FIELD_NUMBER;
    hash = (53 * hash) + getX();
    hash = (37 * hash) + Y_FIELD_NUMBER;
    hash = (53 * hash) + getY();
    if (getEdgesCount() > 0) {
      hash = (37 * hash) + EDGES_FIELD_NUMBER;
      hash = (53 * hash) + getEdgesList().hashCode();
    }
    if (getBlockadesCount() > 0) {
      hash = (37 * hash) + BLOCKADES_FIELD_NUMBER;
      hash = (53 * hash) + getBlockadesList().hashCode();
    }
    if (getApexListCount() > 0) {
      hash = (37 * hash) + APEXLIST_FIELD_NUMBER;
      hash = (53 * hash) + getApexListList().hashCode();
    }
    if (getNeighboursCount() > 0) {
      hash = (37 * hash) + NEIGHBOURS_FIELD_NUMBER;
      hash = (53 * hash) + getNeighboursList().hashCode();
    }
    hash = (37 * hash) + FLOORS_FIELD_NUMBER;
    hash = (53 * hash) + getFloors();
    hash = (37 * hash) + IGNITION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIgnition());
    hash = (37 * hash) + FIERYNESS_FIELD_NUMBER;
    hash = (53 * hash) + getFieryness();
    hash = (37 * hash) + BROKENNESS_FIELD_NUMBER;
    hash = (53 * hash) + getBrokenness();
    hash = (37 * hash) + BUILDINGCODE_FIELD_NUMBER;
    hash = (53 * hash) + getBuildingCode();
    hash = (37 * hash) + BUILDINGATTRIBUTES_FIELD_NUMBER;
    hash = (53 * hash) + getBuildingAttributes();
    hash = (37 * hash) + GROUNDAREA_FIELD_NUMBER;
    hash = (53 * hash) + getGroundArea();
    hash = (37 * hash) + TOTALAREA_FIELD_NUMBER;
    hash = (53 * hash) + getTotalArea();
    hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + getTemperature();
    hash = (37 * hash) + IMPORTANCE_FIELD_NUMBER;
    hash = (53 * hash) + getImportance();
    hash = (37 * hash) + ISONFIRE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsOnFire());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static kernel.AreaProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kernel.AreaProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kernel.AreaProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kernel.AreaProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kernel.AreaProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kernel.AreaProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kernel.AreaProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kernel.AreaProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static kernel.AreaProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static kernel.AreaProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static kernel.AreaProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kernel.AreaProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(kernel.AreaProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code simpleRCRS.AreaProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:simpleRCRS.AreaProto)
      kernel.AreaProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kernel.RCRSProto.internal_static_simpleRCRS_AreaProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kernel.RCRSProto.internal_static_simpleRCRS_AreaProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kernel.AreaProto.class, kernel.AreaProto.Builder.class);
    }

    // Construct using kernel.AreaProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEdgesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      uRN_ = "";

      iD_ = 0;

      x_ = 0;

      y_ = 0;

      if (edgesBuilder_ == null) {
        edges_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        edgesBuilder_.clear();
      }
      blockades_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000002);
      apexList_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000004);
      neighbours_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000008);
      floors_ = 0;

      ignition_ = false;

      fieryness_ = 0;

      brokenness_ = 0;

      buildingCode_ = 0;

      buildingAttributes_ = 0;

      groundArea_ = 0;

      totalArea_ = 0;

      temperature_ = 0;

      importance_ = 0;

      isOnFire_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return kernel.RCRSProto.internal_static_simpleRCRS_AreaProto_descriptor;
    }

    @java.lang.Override
    public kernel.AreaProto getDefaultInstanceForType() {
      return kernel.AreaProto.getDefaultInstance();
    }

    @java.lang.Override
    public kernel.AreaProto build() {
      kernel.AreaProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public kernel.AreaProto buildPartial() {
      kernel.AreaProto result = new kernel.AreaProto(this);
      int from_bitField0_ = bitField0_;
      result.uRN_ = uRN_;
      result.iD_ = iD_;
      result.x_ = x_;
      result.y_ = y_;
      if (edgesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          edges_ = java.util.Collections.unmodifiableList(edges_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.edges_ = edges_;
      } else {
        result.edges_ = edgesBuilder_.build();
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        blockades_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.blockades_ = blockades_;
      if (((bitField0_ & 0x00000004) != 0)) {
        apexList_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.apexList_ = apexList_;
      if (((bitField0_ & 0x00000008) != 0)) {
        neighbours_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.neighbours_ = neighbours_;
      result.floors_ = floors_;
      result.ignition_ = ignition_;
      result.fieryness_ = fieryness_;
      result.brokenness_ = brokenness_;
      result.buildingCode_ = buildingCode_;
      result.buildingAttributes_ = buildingAttributes_;
      result.groundArea_ = groundArea_;
      result.totalArea_ = totalArea_;
      result.temperature_ = temperature_;
      result.importance_ = importance_;
      result.isOnFire_ = isOnFire_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof kernel.AreaProto) {
        return mergeFrom((kernel.AreaProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(kernel.AreaProto other) {
      if (other == kernel.AreaProto.getDefaultInstance()) return this;
      if (!other.getURN().isEmpty()) {
        uRN_ = other.uRN_;
        onChanged();
      }
      if (other.getID() != 0) {
        setID(other.getID());
      }
      if (other.getX() != 0) {
        setX(other.getX());
      }
      if (other.getY() != 0) {
        setY(other.getY());
      }
      if (edgesBuilder_ == null) {
        if (!other.edges_.isEmpty()) {
          if (edges_.isEmpty()) {
            edges_ = other.edges_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEdgesIsMutable();
            edges_.addAll(other.edges_);
          }
          onChanged();
        }
      } else {
        if (!other.edges_.isEmpty()) {
          if (edgesBuilder_.isEmpty()) {
            edgesBuilder_.dispose();
            edgesBuilder_ = null;
            edges_ = other.edges_;
            bitField0_ = (bitField0_ & ~0x00000001);
            edgesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEdgesFieldBuilder() : null;
          } else {
            edgesBuilder_.addAllMessages(other.edges_);
          }
        }
      }
      if (!other.blockades_.isEmpty()) {
        if (blockades_.isEmpty()) {
          blockades_ = other.blockades_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureBlockadesIsMutable();
          blockades_.addAll(other.blockades_);
        }
        onChanged();
      }
      if (!other.apexList_.isEmpty()) {
        if (apexList_.isEmpty()) {
          apexList_ = other.apexList_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureApexListIsMutable();
          apexList_.addAll(other.apexList_);
        }
        onChanged();
      }
      if (!other.neighbours_.isEmpty()) {
        if (neighbours_.isEmpty()) {
          neighbours_ = other.neighbours_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureNeighboursIsMutable();
          neighbours_.addAll(other.neighbours_);
        }
        onChanged();
      }
      if (other.getFloors() != 0) {
        setFloors(other.getFloors());
      }
      if (other.getIgnition() != false) {
        setIgnition(other.getIgnition());
      }
      if (other.getFieryness() != 0) {
        setFieryness(other.getFieryness());
      }
      if (other.getBrokenness() != 0) {
        setBrokenness(other.getBrokenness());
      }
      if (other.getBuildingCode() != 0) {
        setBuildingCode(other.getBuildingCode());
      }
      if (other.getBuildingAttributes() != 0) {
        setBuildingAttributes(other.getBuildingAttributes());
      }
      if (other.getGroundArea() != 0) {
        setGroundArea(other.getGroundArea());
      }
      if (other.getTotalArea() != 0) {
        setTotalArea(other.getTotalArea());
      }
      if (other.getTemperature() != 0) {
        setTemperature(other.getTemperature());
      }
      if (other.getImportance() != 0) {
        setImportance(other.getImportance());
      }
      if (other.getIsOnFire() != false) {
        setIsOnFire(other.getIsOnFire());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      kernel.AreaProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (kernel.AreaProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object uRN_ = "";
    /**
     * <code>string uRN = 1;</code>
     * @return The uRN.
     */
    public java.lang.String getURN() {
      java.lang.Object ref = uRN_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uRN_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string uRN = 1;</code>
     * @return The bytes for uRN.
     */
    public com.google.protobuf.ByteString
        getURNBytes() {
      java.lang.Object ref = uRN_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uRN_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string uRN = 1;</code>
     * @param value The uRN to set.
     * @return This builder for chaining.
     */
    public Builder setURN(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uRN_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string uRN = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearURN() {
      
      uRN_ = getDefaultInstance().getURN();
      onChanged();
      return this;
    }
    /**
     * <code>string uRN = 1;</code>
     * @param value The bytes for uRN to set.
     * @return This builder for chaining.
     */
    public Builder setURNBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      uRN_ = value;
      onChanged();
      return this;
    }

    private int iD_ ;
    /**
     * <code>int32 iD = 2;</code>
     * @return The iD.
     */
    public int getID() {
      return iD_;
    }
    /**
     * <code>int32 iD = 2;</code>
     * @param value The iD to set.
     * @return This builder for chaining.
     */
    public Builder setID(int value) {
      
      iD_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 iD = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearID() {
      
      iD_ = 0;
      onChanged();
      return this;
    }

    private int x_ ;
    /**
     * <code>int32 x = 3;</code>
     * @return The x.
     */
    public int getX() {
      return x_;
    }
    /**
     * <code>int32 x = 3;</code>
     * @param value The x to set.
     * @return This builder for chaining.
     */
    public Builder setX(int value) {
      
      x_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 x = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearX() {
      
      x_ = 0;
      onChanged();
      return this;
    }

    private int y_ ;
    /**
     * <code>int32 y = 4;</code>
     * @return The y.
     */
    public int getY() {
      return y_;
    }
    /**
     * <code>int32 y = 4;</code>
     * @param value The y to set.
     * @return This builder for chaining.
     */
    public Builder setY(int value) {
      
      y_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 y = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearY() {
      
      y_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<kernel.EdgeProto> edges_ =
      java.util.Collections.emptyList();
    private void ensureEdgesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        edges_ = new java.util.ArrayList<kernel.EdgeProto>(edges_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        kernel.EdgeProto, kernel.EdgeProto.Builder, kernel.EdgeProtoOrBuilder> edgesBuilder_;

    /**
     * <code>repeated .simpleRCRS.EdgeProto edges = 5;</code>
     */
    public java.util.List<kernel.EdgeProto> getEdgesList() {
      if (edgesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(edges_);
      } else {
        return edgesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .simpleRCRS.EdgeProto edges = 5;</code>
     */
    public int getEdgesCount() {
      if (edgesBuilder_ == null) {
        return edges_.size();
      } else {
        return edgesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .simpleRCRS.EdgeProto edges = 5;</code>
     */
    public kernel.EdgeProto getEdges(int index) {
      if (edgesBuilder_ == null) {
        return edges_.get(index);
      } else {
        return edgesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .simpleRCRS.EdgeProto edges = 5;</code>
     */
    public Builder setEdges(
        int index, kernel.EdgeProto value) {
      if (edgesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEdgesIsMutable();
        edges_.set(index, value);
        onChanged();
      } else {
        edgesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.EdgeProto edges = 5;</code>
     */
    public Builder setEdges(
        int index, kernel.EdgeProto.Builder builderForValue) {
      if (edgesBuilder_ == null) {
        ensureEdgesIsMutable();
        edges_.set(index, builderForValue.build());
        onChanged();
      } else {
        edgesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.EdgeProto edges = 5;</code>
     */
    public Builder addEdges(kernel.EdgeProto value) {
      if (edgesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEdgesIsMutable();
        edges_.add(value);
        onChanged();
      } else {
        edgesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.EdgeProto edges = 5;</code>
     */
    public Builder addEdges(
        int index, kernel.EdgeProto value) {
      if (edgesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEdgesIsMutable();
        edges_.add(index, value);
        onChanged();
      } else {
        edgesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.EdgeProto edges = 5;</code>
     */
    public Builder addEdges(
        kernel.EdgeProto.Builder builderForValue) {
      if (edgesBuilder_ == null) {
        ensureEdgesIsMutable();
        edges_.add(builderForValue.build());
        onChanged();
      } else {
        edgesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.EdgeProto edges = 5;</code>
     */
    public Builder addEdges(
        int index, kernel.EdgeProto.Builder builderForValue) {
      if (edgesBuilder_ == null) {
        ensureEdgesIsMutable();
        edges_.add(index, builderForValue.build());
        onChanged();
      } else {
        edgesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.EdgeProto edges = 5;</code>
     */
    public Builder addAllEdges(
        java.lang.Iterable<? extends kernel.EdgeProto> values) {
      if (edgesBuilder_ == null) {
        ensureEdgesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, edges_);
        onChanged();
      } else {
        edgesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.EdgeProto edges = 5;</code>
     */
    public Builder clearEdges() {
      if (edgesBuilder_ == null) {
        edges_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        edgesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.EdgeProto edges = 5;</code>
     */
    public Builder removeEdges(int index) {
      if (edgesBuilder_ == null) {
        ensureEdgesIsMutable();
        edges_.remove(index);
        onChanged();
      } else {
        edgesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.EdgeProto edges = 5;</code>
     */
    public kernel.EdgeProto.Builder getEdgesBuilder(
        int index) {
      return getEdgesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .simpleRCRS.EdgeProto edges = 5;</code>
     */
    public kernel.EdgeProtoOrBuilder getEdgesOrBuilder(
        int index) {
      if (edgesBuilder_ == null) {
        return edges_.get(index);  } else {
        return edgesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .simpleRCRS.EdgeProto edges = 5;</code>
     */
    public java.util.List<? extends kernel.EdgeProtoOrBuilder> 
         getEdgesOrBuilderList() {
      if (edgesBuilder_ != null) {
        return edgesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(edges_);
      }
    }
    /**
     * <code>repeated .simpleRCRS.EdgeProto edges = 5;</code>
     */
    public kernel.EdgeProto.Builder addEdgesBuilder() {
      return getEdgesFieldBuilder().addBuilder(
          kernel.EdgeProto.getDefaultInstance());
    }
    /**
     * <code>repeated .simpleRCRS.EdgeProto edges = 5;</code>
     */
    public kernel.EdgeProto.Builder addEdgesBuilder(
        int index) {
      return getEdgesFieldBuilder().addBuilder(
          index, kernel.EdgeProto.getDefaultInstance());
    }
    /**
     * <code>repeated .simpleRCRS.EdgeProto edges = 5;</code>
     */
    public java.util.List<kernel.EdgeProto.Builder> 
         getEdgesBuilderList() {
      return getEdgesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        kernel.EdgeProto, kernel.EdgeProto.Builder, kernel.EdgeProtoOrBuilder> 
        getEdgesFieldBuilder() {
      if (edgesBuilder_ == null) {
        edgesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            kernel.EdgeProto, kernel.EdgeProto.Builder, kernel.EdgeProtoOrBuilder>(
                edges_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        edges_ = null;
      }
      return edgesBuilder_;
    }

    private com.google.protobuf.Internal.IntList blockades_ = emptyIntList();
    private void ensureBlockadesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        blockades_ = mutableCopy(blockades_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated int32 blockades = 6;</code>
     * @return A list containing the blockades.
     */
    public java.util.List<java.lang.Integer>
        getBlockadesList() {
      return ((bitField0_ & 0x00000002) != 0) ?
               java.util.Collections.unmodifiableList(blockades_) : blockades_;
    }
    /**
     * <code>repeated int32 blockades = 6;</code>
     * @return The count of blockades.
     */
    public int getBlockadesCount() {
      return blockades_.size();
    }
    /**
     * <code>repeated int32 blockades = 6;</code>
     * @param index The index of the element to return.
     * @return The blockades at the given index.
     */
    public int getBlockades(int index) {
      return blockades_.getInt(index);
    }
    /**
     * <code>repeated int32 blockades = 6;</code>
     * @param index The index to set the value at.
     * @param value The blockades to set.
     * @return This builder for chaining.
     */
    public Builder setBlockades(
        int index, int value) {
      ensureBlockadesIsMutable();
      blockades_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 blockades = 6;</code>
     * @param value The blockades to add.
     * @return This builder for chaining.
     */
    public Builder addBlockades(int value) {
      ensureBlockadesIsMutable();
      blockades_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 blockades = 6;</code>
     * @param values The blockades to add.
     * @return This builder for chaining.
     */
    public Builder addAllBlockades(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureBlockadesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, blockades_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 blockades = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockades() {
      blockades_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList apexList_ = emptyIntList();
    private void ensureApexListIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        apexList_ = mutableCopy(apexList_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated int32 apexList = 7;</code>
     * @return A list containing the apexList.
     */
    public java.util.List<java.lang.Integer>
        getApexListList() {
      return ((bitField0_ & 0x00000004) != 0) ?
               java.util.Collections.unmodifiableList(apexList_) : apexList_;
    }
    /**
     * <code>repeated int32 apexList = 7;</code>
     * @return The count of apexList.
     */
    public int getApexListCount() {
      return apexList_.size();
    }
    /**
     * <code>repeated int32 apexList = 7;</code>
     * @param index The index of the element to return.
     * @return The apexList at the given index.
     */
    public int getApexList(int index) {
      return apexList_.getInt(index);
    }
    /**
     * <code>repeated int32 apexList = 7;</code>
     * @param index The index to set the value at.
     * @param value The apexList to set.
     * @return This builder for chaining.
     */
    public Builder setApexList(
        int index, int value) {
      ensureApexListIsMutable();
      apexList_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 apexList = 7;</code>
     * @param value The apexList to add.
     * @return This builder for chaining.
     */
    public Builder addApexList(int value) {
      ensureApexListIsMutable();
      apexList_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 apexList = 7;</code>
     * @param values The apexList to add.
     * @return This builder for chaining.
     */
    public Builder addAllApexList(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureApexListIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, apexList_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 apexList = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearApexList() {
      apexList_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList neighbours_ = emptyIntList();
    private void ensureNeighboursIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        neighbours_ = mutableCopy(neighbours_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <code>repeated int32 neighbours = 8;</code>
     * @return A list containing the neighbours.
     */
    public java.util.List<java.lang.Integer>
        getNeighboursList() {
      return ((bitField0_ & 0x00000008) != 0) ?
               java.util.Collections.unmodifiableList(neighbours_) : neighbours_;
    }
    /**
     * <code>repeated int32 neighbours = 8;</code>
     * @return The count of neighbours.
     */
    public int getNeighboursCount() {
      return neighbours_.size();
    }
    /**
     * <code>repeated int32 neighbours = 8;</code>
     * @param index The index of the element to return.
     * @return The neighbours at the given index.
     */
    public int getNeighbours(int index) {
      return neighbours_.getInt(index);
    }
    /**
     * <code>repeated int32 neighbours = 8;</code>
     * @param index The index to set the value at.
     * @param value The neighbours to set.
     * @return This builder for chaining.
     */
    public Builder setNeighbours(
        int index, int value) {
      ensureNeighboursIsMutable();
      neighbours_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 neighbours = 8;</code>
     * @param value The neighbours to add.
     * @return This builder for chaining.
     */
    public Builder addNeighbours(int value) {
      ensureNeighboursIsMutable();
      neighbours_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 neighbours = 8;</code>
     * @param values The neighbours to add.
     * @return This builder for chaining.
     */
    public Builder addAllNeighbours(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureNeighboursIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, neighbours_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 neighbours = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearNeighbours() {
      neighbours_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }

    private int floors_ ;
    /**
     * <pre>
     *&#47;// below for buildings
     * </pre>
     *
     * <code>int32 floors = 9;</code>
     * @return The floors.
     */
    public int getFloors() {
      return floors_;
    }
    /**
     * <pre>
     *&#47;// below for buildings
     * </pre>
     *
     * <code>int32 floors = 9;</code>
     * @param value The floors to set.
     * @return This builder for chaining.
     */
    public Builder setFloors(int value) {
      
      floors_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47;// below for buildings
     * </pre>
     *
     * <code>int32 floors = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearFloors() {
      
      floors_ = 0;
      onChanged();
      return this;
    }

    private boolean ignition_ ;
    /**
     * <code>bool ignition = 10;</code>
     * @return The ignition.
     */
    public boolean getIgnition() {
      return ignition_;
    }
    /**
     * <code>bool ignition = 10;</code>
     * @param value The ignition to set.
     * @return This builder for chaining.
     */
    public Builder setIgnition(boolean value) {
      
      ignition_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool ignition = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearIgnition() {
      
      ignition_ = false;
      onChanged();
      return this;
    }

    private int fieryness_ ;
    /**
     * <code>int32 fieryness = 11;</code>
     * @return The fieryness.
     */
    public int getFieryness() {
      return fieryness_;
    }
    /**
     * <code>int32 fieryness = 11;</code>
     * @param value The fieryness to set.
     * @return This builder for chaining.
     */
    public Builder setFieryness(int value) {
      
      fieryness_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 fieryness = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearFieryness() {
      
      fieryness_ = 0;
      onChanged();
      return this;
    }

    private int brokenness_ ;
    /**
     * <code>int32 brokenness = 12;</code>
     * @return The brokenness.
     */
    public int getBrokenness() {
      return brokenness_;
    }
    /**
     * <code>int32 brokenness = 12;</code>
     * @param value The brokenness to set.
     * @return This builder for chaining.
     */
    public Builder setBrokenness(int value) {
      
      brokenness_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 brokenness = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearBrokenness() {
      
      brokenness_ = 0;
      onChanged();
      return this;
    }

    private int buildingCode_ ;
    /**
     * <code>int32 buildingCode = 13;</code>
     * @return The buildingCode.
     */
    public int getBuildingCode() {
      return buildingCode_;
    }
    /**
     * <code>int32 buildingCode = 13;</code>
     * @param value The buildingCode to set.
     * @return This builder for chaining.
     */
    public Builder setBuildingCode(int value) {
      
      buildingCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 buildingCode = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearBuildingCode() {
      
      buildingCode_ = 0;
      onChanged();
      return this;
    }

    private int buildingAttributes_ ;
    /**
     * <code>int32 buildingAttributes = 14;</code>
     * @return The buildingAttributes.
     */
    public int getBuildingAttributes() {
      return buildingAttributes_;
    }
    /**
     * <code>int32 buildingAttributes = 14;</code>
     * @param value The buildingAttributes to set.
     * @return This builder for chaining.
     */
    public Builder setBuildingAttributes(int value) {
      
      buildingAttributes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 buildingAttributes = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearBuildingAttributes() {
      
      buildingAttributes_ = 0;
      onChanged();
      return this;
    }

    private int groundArea_ ;
    /**
     * <code>int32 groundArea = 15;</code>
     * @return The groundArea.
     */
    public int getGroundArea() {
      return groundArea_;
    }
    /**
     * <code>int32 groundArea = 15;</code>
     * @param value The groundArea to set.
     * @return This builder for chaining.
     */
    public Builder setGroundArea(int value) {
      
      groundArea_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 groundArea = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroundArea() {
      
      groundArea_ = 0;
      onChanged();
      return this;
    }

    private int totalArea_ ;
    /**
     * <code>int32 totalArea = 16;</code>
     * @return The totalArea.
     */
    public int getTotalArea() {
      return totalArea_;
    }
    /**
     * <code>int32 totalArea = 16;</code>
     * @param value The totalArea to set.
     * @return This builder for chaining.
     */
    public Builder setTotalArea(int value) {
      
      totalArea_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 totalArea = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalArea() {
      
      totalArea_ = 0;
      onChanged();
      return this;
    }

    private int temperature_ ;
    /**
     * <code>int32 temperature = 17;</code>
     * @return The temperature.
     */
    public int getTemperature() {
      return temperature_;
    }
    /**
     * <code>int32 temperature = 17;</code>
     * @param value The temperature to set.
     * @return This builder for chaining.
     */
    public Builder setTemperature(int value) {
      
      temperature_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 temperature = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearTemperature() {
      
      temperature_ = 0;
      onChanged();
      return this;
    }

    private int importance_ ;
    /**
     * <code>int32 importance = 18;</code>
     * @return The importance.
     */
    public int getImportance() {
      return importance_;
    }
    /**
     * <code>int32 importance = 18;</code>
     * @param value The importance to set.
     * @return This builder for chaining.
     */
    public Builder setImportance(int value) {
      
      importance_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 importance = 18;</code>
     * @return This builder for chaining.
     */
    public Builder clearImportance() {
      
      importance_ = 0;
      onChanged();
      return this;
    }

    private boolean isOnFire_ ;
    /**
     * <code>bool isOnFire = 19;</code>
     * @return The isOnFire.
     */
    public boolean getIsOnFire() {
      return isOnFire_;
    }
    /**
     * <code>bool isOnFire = 19;</code>
     * @param value The isOnFire to set.
     * @return This builder for chaining.
     */
    public Builder setIsOnFire(boolean value) {
      
      isOnFire_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isOnFire = 19;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsOnFire() {
      
      isOnFire_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:simpleRCRS.AreaProto)
  }

  // @@protoc_insertion_point(class_scope:simpleRCRS.AreaProto)
  private static final kernel.AreaProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new kernel.AreaProto();
  }

  public static kernel.AreaProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AreaProto>
      PARSER = new com.google.protobuf.AbstractParser<AreaProto>() {
    @java.lang.Override
    public AreaProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AreaProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AreaProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AreaProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public kernel.AreaProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

