// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RCRS.proto

package kernel;

public interface BlockadeProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:simpleRCRS.BlockadeProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uRN = 1;</code>
   * @return The uRN.
   */
  java.lang.String getURN();
  /**
   * <code>string uRN = 1;</code>
   * @return The bytes for uRN.
   */
  com.google.protobuf.ByteString
      getURNBytes();

  /**
   * <code>int32 iD = 2;</code>
   * @return The iD.
   */
  int getID();

  /**
   * <code>int32 x = 3;</code>
   * @return The x.
   */
  int getX();

  /**
   * <code>int32 y = 4;</code>
   * @return The y.
   */
  int getY();

  /**
   * <code>int32 cost = 5;</code>
   * @return The cost.
   */
  int getCost();

  /**
   * <code>int32 positionID = 6;</code>
   * @return The positionID.
   */
  int getPositionID();

  /**
   * <code>repeated int32 apexList = 7;</code>
   * @return A list containing the apexList.
   */
  java.util.List<java.lang.Integer> getApexListList();
  /**
   * <code>repeated int32 apexList = 7;</code>
   * @return The count of apexList.
   */
  int getApexListCount();
  /**
   * <code>repeated int32 apexList = 7;</code>
   * @param index The index of the element to return.
   * @return The apexList at the given index.
   */
  int getApexList(int index);
}
