// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RCRS.proto

package kernel;

public interface CheckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:simpleRCRS.Check)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 check = 1;</code>
   * @return The check.
   */
  int getCheck();
}
