// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RCRS.proto

package kernel;

/**
 * Protobuf type {@code simpleRCRS.EdgeProto}
 */
public  final class EdgeProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:simpleRCRS.EdgeProto)
    EdgeProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EdgeProto.newBuilder() to construct.
  private EdgeProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EdgeProto() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EdgeProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EdgeProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            startX_ = input.readInt32();
            break;
          }
          case 16: {

            startY_ = input.readInt32();
            break;
          }
          case 24: {

            endX_ = input.readInt32();
            break;
          }
          case 32: {

            endY_ = input.readInt32();
            break;
          }
          case 40: {

            neighbour_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return kernel.RCRSProto.internal_static_simpleRCRS_EdgeProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return kernel.RCRSProto.internal_static_simpleRCRS_EdgeProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            kernel.EdgeProto.class, kernel.EdgeProto.Builder.class);
  }

  public static final int STARTX_FIELD_NUMBER = 1;
  private int startX_;
  /**
   * <code>int32 startX = 1;</code>
   * @return The startX.
   */
  public int getStartX() {
    return startX_;
  }

  public static final int STARTY_FIELD_NUMBER = 2;
  private int startY_;
  /**
   * <code>int32 startY = 2;</code>
   * @return The startY.
   */
  public int getStartY() {
    return startY_;
  }

  public static final int ENDX_FIELD_NUMBER = 3;
  private int endX_;
  /**
   * <code>int32 endX = 3;</code>
   * @return The endX.
   */
  public int getEndX() {
    return endX_;
  }

  public static final int ENDY_FIELD_NUMBER = 4;
  private int endY_;
  /**
   * <code>int32 endY = 4;</code>
   * @return The endY.
   */
  public int getEndY() {
    return endY_;
  }

  public static final int NEIGHBOUR_FIELD_NUMBER = 5;
  private int neighbour_;
  /**
   * <code>int32 neighbour = 5;</code>
   * @return The neighbour.
   */
  public int getNeighbour() {
    return neighbour_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (startX_ != 0) {
      output.writeInt32(1, startX_);
    }
    if (startY_ != 0) {
      output.writeInt32(2, startY_);
    }
    if (endX_ != 0) {
      output.writeInt32(3, endX_);
    }
    if (endY_ != 0) {
      output.writeInt32(4, endY_);
    }
    if (neighbour_ != 0) {
      output.writeInt32(5, neighbour_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (startX_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, startX_);
    }
    if (startY_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, startY_);
    }
    if (endX_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, endX_);
    }
    if (endY_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, endY_);
    }
    if (neighbour_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, neighbour_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof kernel.EdgeProto)) {
      return super.equals(obj);
    }
    kernel.EdgeProto other = (kernel.EdgeProto) obj;

    if (getStartX()
        != other.getStartX()) return false;
    if (getStartY()
        != other.getStartY()) return false;
    if (getEndX()
        != other.getEndX()) return false;
    if (getEndY()
        != other.getEndY()) return false;
    if (getNeighbour()
        != other.getNeighbour()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STARTX_FIELD_NUMBER;
    hash = (53 * hash) + getStartX();
    hash = (37 * hash) + STARTY_FIELD_NUMBER;
    hash = (53 * hash) + getStartY();
    hash = (37 * hash) + ENDX_FIELD_NUMBER;
    hash = (53 * hash) + getEndX();
    hash = (37 * hash) + ENDY_FIELD_NUMBER;
    hash = (53 * hash) + getEndY();
    hash = (37 * hash) + NEIGHBOUR_FIELD_NUMBER;
    hash = (53 * hash) + getNeighbour();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static kernel.EdgeProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kernel.EdgeProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kernel.EdgeProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kernel.EdgeProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kernel.EdgeProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kernel.EdgeProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kernel.EdgeProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kernel.EdgeProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static kernel.EdgeProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static kernel.EdgeProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static kernel.EdgeProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kernel.EdgeProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(kernel.EdgeProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code simpleRCRS.EdgeProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:simpleRCRS.EdgeProto)
      kernel.EdgeProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kernel.RCRSProto.internal_static_simpleRCRS_EdgeProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kernel.RCRSProto.internal_static_simpleRCRS_EdgeProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kernel.EdgeProto.class, kernel.EdgeProto.Builder.class);
    }

    // Construct using kernel.EdgeProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      startX_ = 0;

      startY_ = 0;

      endX_ = 0;

      endY_ = 0;

      neighbour_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return kernel.RCRSProto.internal_static_simpleRCRS_EdgeProto_descriptor;
    }

    @java.lang.Override
    public kernel.EdgeProto getDefaultInstanceForType() {
      return kernel.EdgeProto.getDefaultInstance();
    }

    @java.lang.Override
    public kernel.EdgeProto build() {
      kernel.EdgeProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public kernel.EdgeProto buildPartial() {
      kernel.EdgeProto result = new kernel.EdgeProto(this);
      result.startX_ = startX_;
      result.startY_ = startY_;
      result.endX_ = endX_;
      result.endY_ = endY_;
      result.neighbour_ = neighbour_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof kernel.EdgeProto) {
        return mergeFrom((kernel.EdgeProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(kernel.EdgeProto other) {
      if (other == kernel.EdgeProto.getDefaultInstance()) return this;
      if (other.getStartX() != 0) {
        setStartX(other.getStartX());
      }
      if (other.getStartY() != 0) {
        setStartY(other.getStartY());
      }
      if (other.getEndX() != 0) {
        setEndX(other.getEndX());
      }
      if (other.getEndY() != 0) {
        setEndY(other.getEndY());
      }
      if (other.getNeighbour() != 0) {
        setNeighbour(other.getNeighbour());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      kernel.EdgeProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (kernel.EdgeProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int startX_ ;
    /**
     * <code>int32 startX = 1;</code>
     * @return The startX.
     */
    public int getStartX() {
      return startX_;
    }
    /**
     * <code>int32 startX = 1;</code>
     * @param value The startX to set.
     * @return This builder for chaining.
     */
    public Builder setStartX(int value) {
      
      startX_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 startX = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartX() {
      
      startX_ = 0;
      onChanged();
      return this;
    }

    private int startY_ ;
    /**
     * <code>int32 startY = 2;</code>
     * @return The startY.
     */
    public int getStartY() {
      return startY_;
    }
    /**
     * <code>int32 startY = 2;</code>
     * @param value The startY to set.
     * @return This builder for chaining.
     */
    public Builder setStartY(int value) {
      
      startY_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 startY = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartY() {
      
      startY_ = 0;
      onChanged();
      return this;
    }

    private int endX_ ;
    /**
     * <code>int32 endX = 3;</code>
     * @return The endX.
     */
    public int getEndX() {
      return endX_;
    }
    /**
     * <code>int32 endX = 3;</code>
     * @param value The endX to set.
     * @return This builder for chaining.
     */
    public Builder setEndX(int value) {
      
      endX_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 endX = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndX() {
      
      endX_ = 0;
      onChanged();
      return this;
    }

    private int endY_ ;
    /**
     * <code>int32 endY = 4;</code>
     * @return The endY.
     */
    public int getEndY() {
      return endY_;
    }
    /**
     * <code>int32 endY = 4;</code>
     * @param value The endY to set.
     * @return This builder for chaining.
     */
    public Builder setEndY(int value) {
      
      endY_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 endY = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndY() {
      
      endY_ = 0;
      onChanged();
      return this;
    }

    private int neighbour_ ;
    /**
     * <code>int32 neighbour = 5;</code>
     * @return The neighbour.
     */
    public int getNeighbour() {
      return neighbour_;
    }
    /**
     * <code>int32 neighbour = 5;</code>
     * @param value The neighbour to set.
     * @return This builder for chaining.
     */
    public Builder setNeighbour(int value) {
      
      neighbour_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 neighbour = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNeighbour() {
      
      neighbour_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:simpleRCRS.EdgeProto)
  }

  // @@protoc_insertion_point(class_scope:simpleRCRS.EdgeProto)
  private static final kernel.EdgeProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new kernel.EdgeProto();
  }

  public static kernel.EdgeProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EdgeProto>
      PARSER = new com.google.protobuf.AbstractParser<EdgeProto>() {
    @java.lang.Override
    public EdgeProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EdgeProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EdgeProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EdgeProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public kernel.EdgeProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

