// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RCRS.proto

package kernel;

public interface HumanProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:simpleRCRS.HumanProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uRN = 1;</code>
   * @return The uRN.
   */
  java.lang.String getURN();
  /**
   * <code>string uRN = 1;</code>
   * @return The bytes for uRN.
   */
  com.google.protobuf.ByteString
      getURNBytes();

  /**
   * <code>int32 iD = 2;</code>
   * @return The iD.
   */
  int getID();

  /**
   * <code>int32 x = 3;</code>
   * @return The x.
   */
  int getX();

  /**
   * <code>int32 y = 4;</code>
   * @return The y.
   */
  int getY();

  /**
   * <code>int32 positionID = 5;</code>
   * @return The positionID.
   */
  int getPositionID();

  /**
   * <code>repeated int32 positionHistory = 6;</code>
   * @return A list containing the positionHistory.
   */
  java.util.List<java.lang.Integer> getPositionHistoryList();
  /**
   * <code>repeated int32 positionHistory = 6;</code>
   * @return The count of positionHistory.
   */
  int getPositionHistoryCount();
  /**
   * <code>repeated int32 positionHistory = 6;</code>
   * @param index The index of the element to return.
   * @return The positionHistory at the given index.
   */
  int getPositionHistory(int index);

  /**
   * <code>int32 travelDistance = 7;</code>
   * @return The travelDistance.
   */
  int getTravelDistance();

  /**
   * <code>int32 buriedness = 8;</code>
   * @return The buriedness.
   */
  int getBuriedness();

  /**
   * <code>int32 damage = 9;</code>
   * @return The damage.
   */
  int getDamage();

  /**
   * <code>int32 hP = 10;</code>
   * @return The hP.
   */
  int getHP();

  /**
   * <code>int32 stamina = 11;</code>
   * @return The stamina.
   */
  int getStamina();

  /**
   * <code>int32 direction = 12;</code>
   * @return The direction.
   */
  int getDirection();

  /**
   * <code>int32 water = 13;</code>
   * @return The water.
   */
  int getWater();
}
