// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RCRS.proto

package kernel;

public interface MoveOrBuilder extends
    // @@protoc_insertion_point(interface_extends:simpleRCRS.Move)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double x = 1;</code>
   * @return The x.
   */
  double getX();

  /**
   * <code>double y = 2;</code>
   * @return The y.
   */
  double getY();
}
