// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RCRS.proto

package kernel;

public interface WorldInfoProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:simpleRCRS.WorldInfoProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
   */
  java.util.List<kernel.AreaProto> 
      getAreasList();
  /**
   * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
   */
  kernel.AreaProto getAreas(int index);
  /**
   * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
   */
  int getAreasCount();
  /**
   * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
   */
  java.util.List<? extends kernel.AreaProtoOrBuilder> 
      getAreasOrBuilderList();
  /**
   * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
   */
  kernel.AreaProtoOrBuilder getAreasOrBuilder(
      int index);

  /**
   * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
   */
  java.util.List<kernel.HumanProto> 
      getHumansList();
  /**
   * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
   */
  kernel.HumanProto getHumans(int index);
  /**
   * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
   */
  int getHumansCount();
  /**
   * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
   */
  java.util.List<? extends kernel.HumanProtoOrBuilder> 
      getHumansOrBuilderList();
  /**
   * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
   */
  kernel.HumanProtoOrBuilder getHumansOrBuilder(
      int index);

  /**
   * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
   */
  java.util.List<kernel.BlockadeProto> 
      getBlockadesList();
  /**
   * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
   */
  kernel.BlockadeProto getBlockades(int index);
  /**
   * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
   */
  int getBlockadesCount();
  /**
   * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
   */
  java.util.List<? extends kernel.BlockadeProtoOrBuilder> 
      getBlockadesOrBuilderList();
  /**
   * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
   */
  kernel.BlockadeProtoOrBuilder getBlockadesOrBuilder(
      int index);

  /**
   * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
   */
  java.util.List<kernel.ElseProto> 
      getElsesList();
  /**
   * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
   */
  kernel.ElseProto getElses(int index);
  /**
   * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
   */
  int getElsesCount();
  /**
   * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
   */
  java.util.List<? extends kernel.ElseProtoOrBuilder> 
      getElsesOrBuilderList();
  /**
   * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
   */
  kernel.ElseProtoOrBuilder getElsesOrBuilder(
      int index);

  /**
   * <code>int32 time = 5;</code>
   * @return The time.
   */
  int getTime();
}
