// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RCRS.proto

package kernel;

/**
 * Protobuf type {@code simpleRCRS.WorldInfoProto}
 */
public  final class WorldInfoProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:simpleRCRS.WorldInfoProto)
    WorldInfoProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WorldInfoProto.newBuilder() to construct.
  private WorldInfoProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WorldInfoProto() {
    areas_ = java.util.Collections.emptyList();
    humans_ = java.util.Collections.emptyList();
    blockades_ = java.util.Collections.emptyList();
    elses_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WorldInfoProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WorldInfoProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              areas_ = new java.util.ArrayList<kernel.AreaProto>();
              mutable_bitField0_ |= 0x00000001;
            }
            areas_.add(
                input.readMessage(kernel.AreaProto.parser(), extensionRegistry));
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              humans_ = new java.util.ArrayList<kernel.HumanProto>();
              mutable_bitField0_ |= 0x00000002;
            }
            humans_.add(
                input.readMessage(kernel.HumanProto.parser(), extensionRegistry));
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              blockades_ = new java.util.ArrayList<kernel.BlockadeProto>();
              mutable_bitField0_ |= 0x00000004;
            }
            blockades_.add(
                input.readMessage(kernel.BlockadeProto.parser(), extensionRegistry));
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              elses_ = new java.util.ArrayList<kernel.ElseProto>();
              mutable_bitField0_ |= 0x00000008;
            }
            elses_.add(
                input.readMessage(kernel.ElseProto.parser(), extensionRegistry));
            break;
          }
          case 40: {

            time_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        areas_ = java.util.Collections.unmodifiableList(areas_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        humans_ = java.util.Collections.unmodifiableList(humans_);
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        blockades_ = java.util.Collections.unmodifiableList(blockades_);
      }
      if (((mutable_bitField0_ & 0x00000008) != 0)) {
        elses_ = java.util.Collections.unmodifiableList(elses_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return kernel.RCRSProto.internal_static_simpleRCRS_WorldInfoProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return kernel.RCRSProto.internal_static_simpleRCRS_WorldInfoProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            kernel.WorldInfoProto.class, kernel.WorldInfoProto.Builder.class);
  }

  public static final int AREAS_FIELD_NUMBER = 1;
  private java.util.List<kernel.AreaProto> areas_;
  /**
   * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
   */
  public java.util.List<kernel.AreaProto> getAreasList() {
    return areas_;
  }
  /**
   * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
   */
  public java.util.List<? extends kernel.AreaProtoOrBuilder> 
      getAreasOrBuilderList() {
    return areas_;
  }
  /**
   * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
   */
  public int getAreasCount() {
    return areas_.size();
  }
  /**
   * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
   */
  public kernel.AreaProto getAreas(int index) {
    return areas_.get(index);
  }
  /**
   * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
   */
  public kernel.AreaProtoOrBuilder getAreasOrBuilder(
      int index) {
    return areas_.get(index);
  }

  public static final int HUMANS_FIELD_NUMBER = 2;
  private java.util.List<kernel.HumanProto> humans_;
  /**
   * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
   */
  public java.util.List<kernel.HumanProto> getHumansList() {
    return humans_;
  }
  /**
   * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
   */
  public java.util.List<? extends kernel.HumanProtoOrBuilder> 
      getHumansOrBuilderList() {
    return humans_;
  }
  /**
   * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
   */
  public int getHumansCount() {
    return humans_.size();
  }
  /**
   * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
   */
  public kernel.HumanProto getHumans(int index) {
    return humans_.get(index);
  }
  /**
   * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
   */
  public kernel.HumanProtoOrBuilder getHumansOrBuilder(
      int index) {
    return humans_.get(index);
  }

  public static final int BLOCKADES_FIELD_NUMBER = 3;
  private java.util.List<kernel.BlockadeProto> blockades_;
  /**
   * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
   */
  public java.util.List<kernel.BlockadeProto> getBlockadesList() {
    return blockades_;
  }
  /**
   * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
   */
  public java.util.List<? extends kernel.BlockadeProtoOrBuilder> 
      getBlockadesOrBuilderList() {
    return blockades_;
  }
  /**
   * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
   */
  public int getBlockadesCount() {
    return blockades_.size();
  }
  /**
   * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
   */
  public kernel.BlockadeProto getBlockades(int index) {
    return blockades_.get(index);
  }
  /**
   * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
   */
  public kernel.BlockadeProtoOrBuilder getBlockadesOrBuilder(
      int index) {
    return blockades_.get(index);
  }

  public static final int ELSES_FIELD_NUMBER = 4;
  private java.util.List<kernel.ElseProto> elses_;
  /**
   * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
   */
  public java.util.List<kernel.ElseProto> getElsesList() {
    return elses_;
  }
  /**
   * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
   */
  public java.util.List<? extends kernel.ElseProtoOrBuilder> 
      getElsesOrBuilderList() {
    return elses_;
  }
  /**
   * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
   */
  public int getElsesCount() {
    return elses_.size();
  }
  /**
   * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
   */
  public kernel.ElseProto getElses(int index) {
    return elses_.get(index);
  }
  /**
   * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
   */
  public kernel.ElseProtoOrBuilder getElsesOrBuilder(
      int index) {
    return elses_.get(index);
  }

  public static final int TIME_FIELD_NUMBER = 5;
  private int time_;
  /**
   * <code>int32 time = 5;</code>
   * @return The time.
   */
  public int getTime() {
    return time_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < areas_.size(); i++) {
      output.writeMessage(1, areas_.get(i));
    }
    for (int i = 0; i < humans_.size(); i++) {
      output.writeMessage(2, humans_.get(i));
    }
    for (int i = 0; i < blockades_.size(); i++) {
      output.writeMessage(3, blockades_.get(i));
    }
    for (int i = 0; i < elses_.size(); i++) {
      output.writeMessage(4, elses_.get(i));
    }
    if (time_ != 0) {
      output.writeInt32(5, time_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < areas_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, areas_.get(i));
    }
    for (int i = 0; i < humans_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, humans_.get(i));
    }
    for (int i = 0; i < blockades_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, blockades_.get(i));
    }
    for (int i = 0; i < elses_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, elses_.get(i));
    }
    if (time_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, time_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof kernel.WorldInfoProto)) {
      return super.equals(obj);
    }
    kernel.WorldInfoProto other = (kernel.WorldInfoProto) obj;

    if (!getAreasList()
        .equals(other.getAreasList())) return false;
    if (!getHumansList()
        .equals(other.getHumansList())) return false;
    if (!getBlockadesList()
        .equals(other.getBlockadesList())) return false;
    if (!getElsesList()
        .equals(other.getElsesList())) return false;
    if (getTime()
        != other.getTime()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAreasCount() > 0) {
      hash = (37 * hash) + AREAS_FIELD_NUMBER;
      hash = (53 * hash) + getAreasList().hashCode();
    }
    if (getHumansCount() > 0) {
      hash = (37 * hash) + HUMANS_FIELD_NUMBER;
      hash = (53 * hash) + getHumansList().hashCode();
    }
    if (getBlockadesCount() > 0) {
      hash = (37 * hash) + BLOCKADES_FIELD_NUMBER;
      hash = (53 * hash) + getBlockadesList().hashCode();
    }
    if (getElsesCount() > 0) {
      hash = (37 * hash) + ELSES_FIELD_NUMBER;
      hash = (53 * hash) + getElsesList().hashCode();
    }
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + getTime();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static kernel.WorldInfoProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kernel.WorldInfoProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kernel.WorldInfoProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kernel.WorldInfoProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kernel.WorldInfoProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kernel.WorldInfoProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kernel.WorldInfoProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kernel.WorldInfoProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static kernel.WorldInfoProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static kernel.WorldInfoProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static kernel.WorldInfoProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kernel.WorldInfoProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(kernel.WorldInfoProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code simpleRCRS.WorldInfoProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:simpleRCRS.WorldInfoProto)
      kernel.WorldInfoProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kernel.RCRSProto.internal_static_simpleRCRS_WorldInfoProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kernel.RCRSProto.internal_static_simpleRCRS_WorldInfoProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kernel.WorldInfoProto.class, kernel.WorldInfoProto.Builder.class);
    }

    // Construct using kernel.WorldInfoProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAreasFieldBuilder();
        getHumansFieldBuilder();
        getBlockadesFieldBuilder();
        getElsesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (areasBuilder_ == null) {
        areas_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        areasBuilder_.clear();
      }
      if (humansBuilder_ == null) {
        humans_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        humansBuilder_.clear();
      }
      if (blockadesBuilder_ == null) {
        blockades_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        blockadesBuilder_.clear();
      }
      if (elsesBuilder_ == null) {
        elses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        elsesBuilder_.clear();
      }
      time_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return kernel.RCRSProto.internal_static_simpleRCRS_WorldInfoProto_descriptor;
    }

    @java.lang.Override
    public kernel.WorldInfoProto getDefaultInstanceForType() {
      return kernel.WorldInfoProto.getDefaultInstance();
    }

    @java.lang.Override
    public kernel.WorldInfoProto build() {
      kernel.WorldInfoProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public kernel.WorldInfoProto buildPartial() {
      kernel.WorldInfoProto result = new kernel.WorldInfoProto(this);
      int from_bitField0_ = bitField0_;
      if (areasBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          areas_ = java.util.Collections.unmodifiableList(areas_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.areas_ = areas_;
      } else {
        result.areas_ = areasBuilder_.build();
      }
      if (humansBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          humans_ = java.util.Collections.unmodifiableList(humans_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.humans_ = humans_;
      } else {
        result.humans_ = humansBuilder_.build();
      }
      if (blockadesBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          blockades_ = java.util.Collections.unmodifiableList(blockades_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.blockades_ = blockades_;
      } else {
        result.blockades_ = blockadesBuilder_.build();
      }
      if (elsesBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          elses_ = java.util.Collections.unmodifiableList(elses_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.elses_ = elses_;
      } else {
        result.elses_ = elsesBuilder_.build();
      }
      result.time_ = time_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof kernel.WorldInfoProto) {
        return mergeFrom((kernel.WorldInfoProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(kernel.WorldInfoProto other) {
      if (other == kernel.WorldInfoProto.getDefaultInstance()) return this;
      if (areasBuilder_ == null) {
        if (!other.areas_.isEmpty()) {
          if (areas_.isEmpty()) {
            areas_ = other.areas_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAreasIsMutable();
            areas_.addAll(other.areas_);
          }
          onChanged();
        }
      } else {
        if (!other.areas_.isEmpty()) {
          if (areasBuilder_.isEmpty()) {
            areasBuilder_.dispose();
            areasBuilder_ = null;
            areas_ = other.areas_;
            bitField0_ = (bitField0_ & ~0x00000001);
            areasBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAreasFieldBuilder() : null;
          } else {
            areasBuilder_.addAllMessages(other.areas_);
          }
        }
      }
      if (humansBuilder_ == null) {
        if (!other.humans_.isEmpty()) {
          if (humans_.isEmpty()) {
            humans_ = other.humans_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureHumansIsMutable();
            humans_.addAll(other.humans_);
          }
          onChanged();
        }
      } else {
        if (!other.humans_.isEmpty()) {
          if (humansBuilder_.isEmpty()) {
            humansBuilder_.dispose();
            humansBuilder_ = null;
            humans_ = other.humans_;
            bitField0_ = (bitField0_ & ~0x00000002);
            humansBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHumansFieldBuilder() : null;
          } else {
            humansBuilder_.addAllMessages(other.humans_);
          }
        }
      }
      if (blockadesBuilder_ == null) {
        if (!other.blockades_.isEmpty()) {
          if (blockades_.isEmpty()) {
            blockades_ = other.blockades_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureBlockadesIsMutable();
            blockades_.addAll(other.blockades_);
          }
          onChanged();
        }
      } else {
        if (!other.blockades_.isEmpty()) {
          if (blockadesBuilder_.isEmpty()) {
            blockadesBuilder_.dispose();
            blockadesBuilder_ = null;
            blockades_ = other.blockades_;
            bitField0_ = (bitField0_ & ~0x00000004);
            blockadesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBlockadesFieldBuilder() : null;
          } else {
            blockadesBuilder_.addAllMessages(other.blockades_);
          }
        }
      }
      if (elsesBuilder_ == null) {
        if (!other.elses_.isEmpty()) {
          if (elses_.isEmpty()) {
            elses_ = other.elses_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureElsesIsMutable();
            elses_.addAll(other.elses_);
          }
          onChanged();
        }
      } else {
        if (!other.elses_.isEmpty()) {
          if (elsesBuilder_.isEmpty()) {
            elsesBuilder_.dispose();
            elsesBuilder_ = null;
            elses_ = other.elses_;
            bitField0_ = (bitField0_ & ~0x00000008);
            elsesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getElsesFieldBuilder() : null;
          } else {
            elsesBuilder_.addAllMessages(other.elses_);
          }
        }
      }
      if (other.getTime() != 0) {
        setTime(other.getTime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      kernel.WorldInfoProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (kernel.WorldInfoProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<kernel.AreaProto> areas_ =
      java.util.Collections.emptyList();
    private void ensureAreasIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        areas_ = new java.util.ArrayList<kernel.AreaProto>(areas_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        kernel.AreaProto, kernel.AreaProto.Builder, kernel.AreaProtoOrBuilder> areasBuilder_;

    /**
     * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
     */
    public java.util.List<kernel.AreaProto> getAreasList() {
      if (areasBuilder_ == null) {
        return java.util.Collections.unmodifiableList(areas_);
      } else {
        return areasBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
     */
    public int getAreasCount() {
      if (areasBuilder_ == null) {
        return areas_.size();
      } else {
        return areasBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
     */
    public kernel.AreaProto getAreas(int index) {
      if (areasBuilder_ == null) {
        return areas_.get(index);
      } else {
        return areasBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
     */
    public Builder setAreas(
        int index, kernel.AreaProto value) {
      if (areasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAreasIsMutable();
        areas_.set(index, value);
        onChanged();
      } else {
        areasBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
     */
    public Builder setAreas(
        int index, kernel.AreaProto.Builder builderForValue) {
      if (areasBuilder_ == null) {
        ensureAreasIsMutable();
        areas_.set(index, builderForValue.build());
        onChanged();
      } else {
        areasBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
     */
    public Builder addAreas(kernel.AreaProto value) {
      if (areasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAreasIsMutable();
        areas_.add(value);
        onChanged();
      } else {
        areasBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
     */
    public Builder addAreas(
        int index, kernel.AreaProto value) {
      if (areasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAreasIsMutable();
        areas_.add(index, value);
        onChanged();
      } else {
        areasBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
     */
    public Builder addAreas(
        kernel.AreaProto.Builder builderForValue) {
      if (areasBuilder_ == null) {
        ensureAreasIsMutable();
        areas_.add(builderForValue.build());
        onChanged();
      } else {
        areasBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
     */
    public Builder addAreas(
        int index, kernel.AreaProto.Builder builderForValue) {
      if (areasBuilder_ == null) {
        ensureAreasIsMutable();
        areas_.add(index, builderForValue.build());
        onChanged();
      } else {
        areasBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
     */
    public Builder addAllAreas(
        java.lang.Iterable<? extends kernel.AreaProto> values) {
      if (areasBuilder_ == null) {
        ensureAreasIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, areas_);
        onChanged();
      } else {
        areasBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
     */
    public Builder clearAreas() {
      if (areasBuilder_ == null) {
        areas_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        areasBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
     */
    public Builder removeAreas(int index) {
      if (areasBuilder_ == null) {
        ensureAreasIsMutable();
        areas_.remove(index);
        onChanged();
      } else {
        areasBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
     */
    public kernel.AreaProto.Builder getAreasBuilder(
        int index) {
      return getAreasFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
     */
    public kernel.AreaProtoOrBuilder getAreasOrBuilder(
        int index) {
      if (areasBuilder_ == null) {
        return areas_.get(index);  } else {
        return areasBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
     */
    public java.util.List<? extends kernel.AreaProtoOrBuilder> 
         getAreasOrBuilderList() {
      if (areasBuilder_ != null) {
        return areasBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(areas_);
      }
    }
    /**
     * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
     */
    public kernel.AreaProto.Builder addAreasBuilder() {
      return getAreasFieldBuilder().addBuilder(
          kernel.AreaProto.getDefaultInstance());
    }
    /**
     * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
     */
    public kernel.AreaProto.Builder addAreasBuilder(
        int index) {
      return getAreasFieldBuilder().addBuilder(
          index, kernel.AreaProto.getDefaultInstance());
    }
    /**
     * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
     */
    public java.util.List<kernel.AreaProto.Builder> 
         getAreasBuilderList() {
      return getAreasFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        kernel.AreaProto, kernel.AreaProto.Builder, kernel.AreaProtoOrBuilder> 
        getAreasFieldBuilder() {
      if (areasBuilder_ == null) {
        areasBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            kernel.AreaProto, kernel.AreaProto.Builder, kernel.AreaProtoOrBuilder>(
                areas_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        areas_ = null;
      }
      return areasBuilder_;
    }

    private java.util.List<kernel.HumanProto> humans_ =
      java.util.Collections.emptyList();
    private void ensureHumansIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        humans_ = new java.util.ArrayList<kernel.HumanProto>(humans_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        kernel.HumanProto, kernel.HumanProto.Builder, kernel.HumanProtoOrBuilder> humansBuilder_;

    /**
     * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
     */
    public java.util.List<kernel.HumanProto> getHumansList() {
      if (humansBuilder_ == null) {
        return java.util.Collections.unmodifiableList(humans_);
      } else {
        return humansBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
     */
    public int getHumansCount() {
      if (humansBuilder_ == null) {
        return humans_.size();
      } else {
        return humansBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
     */
    public kernel.HumanProto getHumans(int index) {
      if (humansBuilder_ == null) {
        return humans_.get(index);
      } else {
        return humansBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
     */
    public Builder setHumans(
        int index, kernel.HumanProto value) {
      if (humansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHumansIsMutable();
        humans_.set(index, value);
        onChanged();
      } else {
        humansBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
     */
    public Builder setHumans(
        int index, kernel.HumanProto.Builder builderForValue) {
      if (humansBuilder_ == null) {
        ensureHumansIsMutable();
        humans_.set(index, builderForValue.build());
        onChanged();
      } else {
        humansBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
     */
    public Builder addHumans(kernel.HumanProto value) {
      if (humansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHumansIsMutable();
        humans_.add(value);
        onChanged();
      } else {
        humansBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
     */
    public Builder addHumans(
        int index, kernel.HumanProto value) {
      if (humansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHumansIsMutable();
        humans_.add(index, value);
        onChanged();
      } else {
        humansBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
     */
    public Builder addHumans(
        kernel.HumanProto.Builder builderForValue) {
      if (humansBuilder_ == null) {
        ensureHumansIsMutable();
        humans_.add(builderForValue.build());
        onChanged();
      } else {
        humansBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
     */
    public Builder addHumans(
        int index, kernel.HumanProto.Builder builderForValue) {
      if (humansBuilder_ == null) {
        ensureHumansIsMutable();
        humans_.add(index, builderForValue.build());
        onChanged();
      } else {
        humansBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
     */
    public Builder addAllHumans(
        java.lang.Iterable<? extends kernel.HumanProto> values) {
      if (humansBuilder_ == null) {
        ensureHumansIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, humans_);
        onChanged();
      } else {
        humansBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
     */
    public Builder clearHumans() {
      if (humansBuilder_ == null) {
        humans_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        humansBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
     */
    public Builder removeHumans(int index) {
      if (humansBuilder_ == null) {
        ensureHumansIsMutable();
        humans_.remove(index);
        onChanged();
      } else {
        humansBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
     */
    public kernel.HumanProto.Builder getHumansBuilder(
        int index) {
      return getHumansFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
     */
    public kernel.HumanProtoOrBuilder getHumansOrBuilder(
        int index) {
      if (humansBuilder_ == null) {
        return humans_.get(index);  } else {
        return humansBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
     */
    public java.util.List<? extends kernel.HumanProtoOrBuilder> 
         getHumansOrBuilderList() {
      if (humansBuilder_ != null) {
        return humansBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(humans_);
      }
    }
    /**
     * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
     */
    public kernel.HumanProto.Builder addHumansBuilder() {
      return getHumansFieldBuilder().addBuilder(
          kernel.HumanProto.getDefaultInstance());
    }
    /**
     * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
     */
    public kernel.HumanProto.Builder addHumansBuilder(
        int index) {
      return getHumansFieldBuilder().addBuilder(
          index, kernel.HumanProto.getDefaultInstance());
    }
    /**
     * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
     */
    public java.util.List<kernel.HumanProto.Builder> 
         getHumansBuilderList() {
      return getHumansFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        kernel.HumanProto, kernel.HumanProto.Builder, kernel.HumanProtoOrBuilder> 
        getHumansFieldBuilder() {
      if (humansBuilder_ == null) {
        humansBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            kernel.HumanProto, kernel.HumanProto.Builder, kernel.HumanProtoOrBuilder>(
                humans_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        humans_ = null;
      }
      return humansBuilder_;
    }

    private java.util.List<kernel.BlockadeProto> blockades_ =
      java.util.Collections.emptyList();
    private void ensureBlockadesIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        blockades_ = new java.util.ArrayList<kernel.BlockadeProto>(blockades_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        kernel.BlockadeProto, kernel.BlockadeProto.Builder, kernel.BlockadeProtoOrBuilder> blockadesBuilder_;

    /**
     * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
     */
    public java.util.List<kernel.BlockadeProto> getBlockadesList() {
      if (blockadesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(blockades_);
      } else {
        return blockadesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
     */
    public int getBlockadesCount() {
      if (blockadesBuilder_ == null) {
        return blockades_.size();
      } else {
        return blockadesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
     */
    public kernel.BlockadeProto getBlockades(int index) {
      if (blockadesBuilder_ == null) {
        return blockades_.get(index);
      } else {
        return blockadesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
     */
    public Builder setBlockades(
        int index, kernel.BlockadeProto value) {
      if (blockadesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlockadesIsMutable();
        blockades_.set(index, value);
        onChanged();
      } else {
        blockadesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
     */
    public Builder setBlockades(
        int index, kernel.BlockadeProto.Builder builderForValue) {
      if (blockadesBuilder_ == null) {
        ensureBlockadesIsMutable();
        blockades_.set(index, builderForValue.build());
        onChanged();
      } else {
        blockadesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
     */
    public Builder addBlockades(kernel.BlockadeProto value) {
      if (blockadesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlockadesIsMutable();
        blockades_.add(value);
        onChanged();
      } else {
        blockadesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
     */
    public Builder addBlockades(
        int index, kernel.BlockadeProto value) {
      if (blockadesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBlockadesIsMutable();
        blockades_.add(index, value);
        onChanged();
      } else {
        blockadesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
     */
    public Builder addBlockades(
        kernel.BlockadeProto.Builder builderForValue) {
      if (blockadesBuilder_ == null) {
        ensureBlockadesIsMutable();
        blockades_.add(builderForValue.build());
        onChanged();
      } else {
        blockadesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
     */
    public Builder addBlockades(
        int index, kernel.BlockadeProto.Builder builderForValue) {
      if (blockadesBuilder_ == null) {
        ensureBlockadesIsMutable();
        blockades_.add(index, builderForValue.build());
        onChanged();
      } else {
        blockadesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
     */
    public Builder addAllBlockades(
        java.lang.Iterable<? extends kernel.BlockadeProto> values) {
      if (blockadesBuilder_ == null) {
        ensureBlockadesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, blockades_);
        onChanged();
      } else {
        blockadesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
     */
    public Builder clearBlockades() {
      if (blockadesBuilder_ == null) {
        blockades_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        blockadesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
     */
    public Builder removeBlockades(int index) {
      if (blockadesBuilder_ == null) {
        ensureBlockadesIsMutable();
        blockades_.remove(index);
        onChanged();
      } else {
        blockadesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
     */
    public kernel.BlockadeProto.Builder getBlockadesBuilder(
        int index) {
      return getBlockadesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
     */
    public kernel.BlockadeProtoOrBuilder getBlockadesOrBuilder(
        int index) {
      if (blockadesBuilder_ == null) {
        return blockades_.get(index);  } else {
        return blockadesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
     */
    public java.util.List<? extends kernel.BlockadeProtoOrBuilder> 
         getBlockadesOrBuilderList() {
      if (blockadesBuilder_ != null) {
        return blockadesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(blockades_);
      }
    }
    /**
     * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
     */
    public kernel.BlockadeProto.Builder addBlockadesBuilder() {
      return getBlockadesFieldBuilder().addBuilder(
          kernel.BlockadeProto.getDefaultInstance());
    }
    /**
     * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
     */
    public kernel.BlockadeProto.Builder addBlockadesBuilder(
        int index) {
      return getBlockadesFieldBuilder().addBuilder(
          index, kernel.BlockadeProto.getDefaultInstance());
    }
    /**
     * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
     */
    public java.util.List<kernel.BlockadeProto.Builder> 
         getBlockadesBuilderList() {
      return getBlockadesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        kernel.BlockadeProto, kernel.BlockadeProto.Builder, kernel.BlockadeProtoOrBuilder> 
        getBlockadesFieldBuilder() {
      if (blockadesBuilder_ == null) {
        blockadesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            kernel.BlockadeProto, kernel.BlockadeProto.Builder, kernel.BlockadeProtoOrBuilder>(
                blockades_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        blockades_ = null;
      }
      return blockadesBuilder_;
    }

    private java.util.List<kernel.ElseProto> elses_ =
      java.util.Collections.emptyList();
    private void ensureElsesIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        elses_ = new java.util.ArrayList<kernel.ElseProto>(elses_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        kernel.ElseProto, kernel.ElseProto.Builder, kernel.ElseProtoOrBuilder> elsesBuilder_;

    /**
     * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
     */
    public java.util.List<kernel.ElseProto> getElsesList() {
      if (elsesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(elses_);
      } else {
        return elsesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
     */
    public int getElsesCount() {
      if (elsesBuilder_ == null) {
        return elses_.size();
      } else {
        return elsesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
     */
    public kernel.ElseProto getElses(int index) {
      if (elsesBuilder_ == null) {
        return elses_.get(index);
      } else {
        return elsesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
     */
    public Builder setElses(
        int index, kernel.ElseProto value) {
      if (elsesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureElsesIsMutable();
        elses_.set(index, value);
        onChanged();
      } else {
        elsesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
     */
    public Builder setElses(
        int index, kernel.ElseProto.Builder builderForValue) {
      if (elsesBuilder_ == null) {
        ensureElsesIsMutable();
        elses_.set(index, builderForValue.build());
        onChanged();
      } else {
        elsesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
     */
    public Builder addElses(kernel.ElseProto value) {
      if (elsesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureElsesIsMutable();
        elses_.add(value);
        onChanged();
      } else {
        elsesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
     */
    public Builder addElses(
        int index, kernel.ElseProto value) {
      if (elsesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureElsesIsMutable();
        elses_.add(index, value);
        onChanged();
      } else {
        elsesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
     */
    public Builder addElses(
        kernel.ElseProto.Builder builderForValue) {
      if (elsesBuilder_ == null) {
        ensureElsesIsMutable();
        elses_.add(builderForValue.build());
        onChanged();
      } else {
        elsesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
     */
    public Builder addElses(
        int index, kernel.ElseProto.Builder builderForValue) {
      if (elsesBuilder_ == null) {
        ensureElsesIsMutable();
        elses_.add(index, builderForValue.build());
        onChanged();
      } else {
        elsesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
     */
    public Builder addAllElses(
        java.lang.Iterable<? extends kernel.ElseProto> values) {
      if (elsesBuilder_ == null) {
        ensureElsesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, elses_);
        onChanged();
      } else {
        elsesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
     */
    public Builder clearElses() {
      if (elsesBuilder_ == null) {
        elses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        elsesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
     */
    public Builder removeElses(int index) {
      if (elsesBuilder_ == null) {
        ensureElsesIsMutable();
        elses_.remove(index);
        onChanged();
      } else {
        elsesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
     */
    public kernel.ElseProto.Builder getElsesBuilder(
        int index) {
      return getElsesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
     */
    public kernel.ElseProtoOrBuilder getElsesOrBuilder(
        int index) {
      if (elsesBuilder_ == null) {
        return elses_.get(index);  } else {
        return elsesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
     */
    public java.util.List<? extends kernel.ElseProtoOrBuilder> 
         getElsesOrBuilderList() {
      if (elsesBuilder_ != null) {
        return elsesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(elses_);
      }
    }
    /**
     * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
     */
    public kernel.ElseProto.Builder addElsesBuilder() {
      return getElsesFieldBuilder().addBuilder(
          kernel.ElseProto.getDefaultInstance());
    }
    /**
     * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
     */
    public kernel.ElseProto.Builder addElsesBuilder(
        int index) {
      return getElsesFieldBuilder().addBuilder(
          index, kernel.ElseProto.getDefaultInstance());
    }
    /**
     * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
     */
    public java.util.List<kernel.ElseProto.Builder> 
         getElsesBuilderList() {
      return getElsesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        kernel.ElseProto, kernel.ElseProto.Builder, kernel.ElseProtoOrBuilder> 
        getElsesFieldBuilder() {
      if (elsesBuilder_ == null) {
        elsesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            kernel.ElseProto, kernel.ElseProto.Builder, kernel.ElseProtoOrBuilder>(
                elses_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        elses_ = null;
      }
      return elsesBuilder_;
    }

    private int time_ ;
    /**
     * <code>int32 time = 5;</code>
     * @return The time.
     */
    public int getTime() {
      return time_;
    }
    /**
     * <code>int32 time = 5;</code>
     * @param value The time to set.
     * @return This builder for chaining.
     */
    public Builder setTime(int value) {
      
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 time = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTime() {
      
      time_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:simpleRCRS.WorldInfoProto)
  }

  // @@protoc_insertion_point(class_scope:simpleRCRS.WorldInfoProto)
  private static final kernel.WorldInfoProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new kernel.WorldInfoProto();
  }

  public static kernel.WorldInfoProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WorldInfoProto>
      PARSER = new com.google.protobuf.AbstractParser<WorldInfoProto>() {
    @java.lang.Override
    public WorldInfoProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WorldInfoProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WorldInfoProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WorldInfoProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public kernel.WorldInfoProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

