// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: firebrigade.proto

package adf.sample.tactics;

public interface ActionTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:simpleRCRS.ActionType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 actionType = 1;</code>
   * @return The actionType.
   */
  int getActionType();

  /**
   * <code>double x = 2;</code>
   * @return The x.
   */
  double getX();

  /**
   * <code>double y = 3;</code>
   * @return The y.
   */
  double getY();
}
