// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: firebrigade.proto

package adf.sample.tactics;

public interface EdgeProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:simpleRCRS.EdgeProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 startX = 1;</code>
   * @return The startX.
   */
  int getStartX();

  /**
   * <code>int32 startY = 2;</code>
   * @return The startY.
   */
  int getStartY();

  /**
   * <code>int32 endX = 3;</code>
   * @return The endX.
   */
  int getEndX();

  /**
   * <code>int32 endY = 4;</code>
   * @return The endY.
   */
  int getEndY();

  /**
   * <code>int32 neighbour = 5;</code>
   * @return The neighbour.
   */
  int getNeighbour();
}
