// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: firebrigade.proto

package adf.sample.tactics;

public interface ElseProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:simpleRCRS.ElseProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uRN = 1;</code>
   * @return The uRN.
   */
  java.lang.String getURN();
  /**
   * <code>string uRN = 1;</code>
   * @return The bytes for uRN.
   */
  com.google.protobuf.ByteString
      getURNBytes();

  /**
   * <code>int32 iD = 2;</code>
   * @return The iD.
   */
  int getID();
}
