// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: firebrigade.proto

package adf.sample.tactics;

/**
 * Protobuf type {@code simpleRCRS.HumanProto}
 */
public  final class HumanProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:simpleRCRS.HumanProto)
    HumanProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HumanProto.newBuilder() to construct.
  private HumanProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HumanProto() {
    uRN_ = "";
    positionHistory_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HumanProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HumanProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            uRN_ = s;
            break;
          }
          case 16: {

            iD_ = input.readInt32();
            break;
          }
          case 24: {

            x_ = input.readInt32();
            break;
          }
          case 32: {

            y_ = input.readInt32();
            break;
          }
          case 40: {

            positionID_ = input.readInt32();
            break;
          }
          case 48: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              positionHistory_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            positionHistory_.addInt(input.readInt32());
            break;
          }
          case 50: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              positionHistory_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              positionHistory_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 56: {

            travelDistance_ = input.readInt32();
            break;
          }
          case 64: {

            buriedness_ = input.readInt32();
            break;
          }
          case 72: {

            damage_ = input.readInt32();
            break;
          }
          case 80: {

            hP_ = input.readInt32();
            break;
          }
          case 88: {

            stamina_ = input.readInt32();
            break;
          }
          case 96: {

            direction_ = input.readInt32();
            break;
          }
          case 104: {

            water_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        positionHistory_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return adf.sample.tactics.firebrigadeProto.internal_static_simpleRCRS_HumanProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return adf.sample.tactics.firebrigadeProto.internal_static_simpleRCRS_HumanProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            adf.sample.tactics.HumanProto.class, adf.sample.tactics.HumanProto.Builder.class);
  }

  public static final int URN_FIELD_NUMBER = 1;
  private volatile java.lang.Object uRN_;
  /**
   * <code>string uRN = 1;</code>
   * @return The uRN.
   */
  public java.lang.String getURN() {
    java.lang.Object ref = uRN_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uRN_ = s;
      return s;
    }
  }
  /**
   * <code>string uRN = 1;</code>
   * @return The bytes for uRN.
   */
  public com.google.protobuf.ByteString
      getURNBytes() {
    java.lang.Object ref = uRN_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uRN_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 2;
  private int iD_;
  /**
   * <code>int32 iD = 2;</code>
   * @return The iD.
   */
  public int getID() {
    return iD_;
  }

  public static final int X_FIELD_NUMBER = 3;
  private int x_;
  /**
   * <code>int32 x = 3;</code>
   * @return The x.
   */
  public int getX() {
    return x_;
  }

  public static final int Y_FIELD_NUMBER = 4;
  private int y_;
  /**
   * <code>int32 y = 4;</code>
   * @return The y.
   */
  public int getY() {
    return y_;
  }

  public static final int POSITIONID_FIELD_NUMBER = 5;
  private int positionID_;
  /**
   * <code>int32 positionID = 5;</code>
   * @return The positionID.
   */
  public int getPositionID() {
    return positionID_;
  }

  public static final int POSITIONHISTORY_FIELD_NUMBER = 6;
  private com.google.protobuf.Internal.IntList positionHistory_;
  /**
   * <code>repeated int32 positionHistory = 6;</code>
   * @return A list containing the positionHistory.
   */
  public java.util.List<java.lang.Integer>
      getPositionHistoryList() {
    return positionHistory_;
  }
  /**
   * <code>repeated int32 positionHistory = 6;</code>
   * @return The count of positionHistory.
   */
  public int getPositionHistoryCount() {
    return positionHistory_.size();
  }
  /**
   * <code>repeated int32 positionHistory = 6;</code>
   * @param index The index of the element to return.
   * @return The positionHistory at the given index.
   */
  public int getPositionHistory(int index) {
    return positionHistory_.getInt(index);
  }
  private int positionHistoryMemoizedSerializedSize = -1;

  public static final int TRAVELDISTANCE_FIELD_NUMBER = 7;
  private int travelDistance_;
  /**
   * <code>int32 travelDistance = 7;</code>
   * @return The travelDistance.
   */
  public int getTravelDistance() {
    return travelDistance_;
  }

  public static final int BURIEDNESS_FIELD_NUMBER = 8;
  private int buriedness_;
  /**
   * <code>int32 buriedness = 8;</code>
   * @return The buriedness.
   */
  public int getBuriedness() {
    return buriedness_;
  }

  public static final int DAMAGE_FIELD_NUMBER = 9;
  private int damage_;
  /**
   * <code>int32 damage = 9;</code>
   * @return The damage.
   */
  public int getDamage() {
    return damage_;
  }

  public static final int HP_FIELD_NUMBER = 10;
  private int hP_;
  /**
   * <code>int32 hP = 10;</code>
   * @return The hP.
   */
  public int getHP() {
    return hP_;
  }

  public static final int STAMINA_FIELD_NUMBER = 11;
  private int stamina_;
  /**
   * <code>int32 stamina = 11;</code>
   * @return The stamina.
   */
  public int getStamina() {
    return stamina_;
  }

  public static final int DIRECTION_FIELD_NUMBER = 12;
  private int direction_;
  /**
   * <code>int32 direction = 12;</code>
   * @return The direction.
   */
  public int getDirection() {
    return direction_;
  }

  public static final int WATER_FIELD_NUMBER = 13;
  private int water_;
  /**
   * <code>int32 water = 13;</code>
   * @return The water.
   */
  public int getWater() {
    return water_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!getURNBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uRN_);
    }
    if (iD_ != 0) {
      output.writeInt32(2, iD_);
    }
    if (x_ != 0) {
      output.writeInt32(3, x_);
    }
    if (y_ != 0) {
      output.writeInt32(4, y_);
    }
    if (positionID_ != 0) {
      output.writeInt32(5, positionID_);
    }
    if (getPositionHistoryList().size() > 0) {
      output.writeUInt32NoTag(50);
      output.writeUInt32NoTag(positionHistoryMemoizedSerializedSize);
    }
    for (int i = 0; i < positionHistory_.size(); i++) {
      output.writeInt32NoTag(positionHistory_.getInt(i));
    }
    if (travelDistance_ != 0) {
      output.writeInt32(7, travelDistance_);
    }
    if (buriedness_ != 0) {
      output.writeInt32(8, buriedness_);
    }
    if (damage_ != 0) {
      output.writeInt32(9, damage_);
    }
    if (hP_ != 0) {
      output.writeInt32(10, hP_);
    }
    if (stamina_ != 0) {
      output.writeInt32(11, stamina_);
    }
    if (direction_ != 0) {
      output.writeInt32(12, direction_);
    }
    if (water_ != 0) {
      output.writeInt32(13, water_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getURNBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uRN_);
    }
    if (iD_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, iD_);
    }
    if (x_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, x_);
    }
    if (y_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, y_);
    }
    if (positionID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, positionID_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < positionHistory_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(positionHistory_.getInt(i));
      }
      size += dataSize;
      if (!getPositionHistoryList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      positionHistoryMemoizedSerializedSize = dataSize;
    }
    if (travelDistance_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, travelDistance_);
    }
    if (buriedness_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, buriedness_);
    }
    if (damage_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, damage_);
    }
    if (hP_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, hP_);
    }
    if (stamina_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, stamina_);
    }
    if (direction_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, direction_);
    }
    if (water_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(13, water_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof adf.sample.tactics.HumanProto)) {
      return super.equals(obj);
    }
    adf.sample.tactics.HumanProto other = (adf.sample.tactics.HumanProto) obj;

    if (!getURN()
        .equals(other.getURN())) return false;
    if (getID()
        != other.getID()) return false;
    if (getX()
        != other.getX()) return false;
    if (getY()
        != other.getY()) return false;
    if (getPositionID()
        != other.getPositionID()) return false;
    if (!getPositionHistoryList()
        .equals(other.getPositionHistoryList())) return false;
    if (getTravelDistance()
        != other.getTravelDistance()) return false;
    if (getBuriedness()
        != other.getBuriedness()) return false;
    if (getDamage()
        != other.getDamage()) return false;
    if (getHP()
        != other.getHP()) return false;
    if (getStamina()
        != other.getStamina()) return false;
    if (getDirection()
        != other.getDirection()) return false;
    if (getWater()
        != other.getWater()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + URN_FIELD_NUMBER;
    hash = (53 * hash) + getURN().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getID();
    hash = (37 * hash) + X_FIELD_NUMBER;
    hash = (53 * hash) + getX();
    hash = (37 * hash) + Y_FIELD_NUMBER;
    hash = (53 * hash) + getY();
    hash = (37 * hash) + POSITIONID_FIELD_NUMBER;
    hash = (53 * hash) + getPositionID();
    if (getPositionHistoryCount() > 0) {
      hash = (37 * hash) + POSITIONHISTORY_FIELD_NUMBER;
      hash = (53 * hash) + getPositionHistoryList().hashCode();
    }
    hash = (37 * hash) + TRAVELDISTANCE_FIELD_NUMBER;
    hash = (53 * hash) + getTravelDistance();
    hash = (37 * hash) + BURIEDNESS_FIELD_NUMBER;
    hash = (53 * hash) + getBuriedness();
    hash = (37 * hash) + DAMAGE_FIELD_NUMBER;
    hash = (53 * hash) + getDamage();
    hash = (37 * hash) + HP_FIELD_NUMBER;
    hash = (53 * hash) + getHP();
    hash = (37 * hash) + STAMINA_FIELD_NUMBER;
    hash = (53 * hash) + getStamina();
    hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
    hash = (53 * hash) + getDirection();
    hash = (37 * hash) + WATER_FIELD_NUMBER;
    hash = (53 * hash) + getWater();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static adf.sample.tactics.HumanProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static adf.sample.tactics.HumanProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static adf.sample.tactics.HumanProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static adf.sample.tactics.HumanProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static adf.sample.tactics.HumanProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static adf.sample.tactics.HumanProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static adf.sample.tactics.HumanProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static adf.sample.tactics.HumanProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static adf.sample.tactics.HumanProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static adf.sample.tactics.HumanProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static adf.sample.tactics.HumanProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static adf.sample.tactics.HumanProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(adf.sample.tactics.HumanProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code simpleRCRS.HumanProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:simpleRCRS.HumanProto)
      adf.sample.tactics.HumanProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return adf.sample.tactics.firebrigadeProto.internal_static_simpleRCRS_HumanProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return adf.sample.tactics.firebrigadeProto.internal_static_simpleRCRS_HumanProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              adf.sample.tactics.HumanProto.class, adf.sample.tactics.HumanProto.Builder.class);
    }

    // Construct using adf.sample.tactics.HumanProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      uRN_ = "";

      iD_ = 0;

      x_ = 0;

      y_ = 0;

      positionID_ = 0;

      positionHistory_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      travelDistance_ = 0;

      buriedness_ = 0;

      damage_ = 0;

      hP_ = 0;

      stamina_ = 0;

      direction_ = 0;

      water_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return adf.sample.tactics.firebrigadeProto.internal_static_simpleRCRS_HumanProto_descriptor;
    }

    @java.lang.Override
    public adf.sample.tactics.HumanProto getDefaultInstanceForType() {
      return adf.sample.tactics.HumanProto.getDefaultInstance();
    }

    @java.lang.Override
    public adf.sample.tactics.HumanProto build() {
      adf.sample.tactics.HumanProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public adf.sample.tactics.HumanProto buildPartial() {
      adf.sample.tactics.HumanProto result = new adf.sample.tactics.HumanProto(this);
      int from_bitField0_ = bitField0_;
      result.uRN_ = uRN_;
      result.iD_ = iD_;
      result.x_ = x_;
      result.y_ = y_;
      result.positionID_ = positionID_;
      if (((bitField0_ & 0x00000001) != 0)) {
        positionHistory_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.positionHistory_ = positionHistory_;
      result.travelDistance_ = travelDistance_;
      result.buriedness_ = buriedness_;
      result.damage_ = damage_;
      result.hP_ = hP_;
      result.stamina_ = stamina_;
      result.direction_ = direction_;
      result.water_ = water_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof adf.sample.tactics.HumanProto) {
        return mergeFrom((adf.sample.tactics.HumanProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(adf.sample.tactics.HumanProto other) {
      if (other == adf.sample.tactics.HumanProto.getDefaultInstance()) return this;
      if (!other.getURN().isEmpty()) {
        uRN_ = other.uRN_;
        onChanged();
      }
      if (other.getID() != 0) {
        setID(other.getID());
      }
      if (other.getX() != 0) {
        setX(other.getX());
      }
      if (other.getY() != 0) {
        setY(other.getY());
      }
      if (other.getPositionID() != 0) {
        setPositionID(other.getPositionID());
      }
      if (!other.positionHistory_.isEmpty()) {
        if (positionHistory_.isEmpty()) {
          positionHistory_ = other.positionHistory_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensurePositionHistoryIsMutable();
          positionHistory_.addAll(other.positionHistory_);
        }
        onChanged();
      }
      if (other.getTravelDistance() != 0) {
        setTravelDistance(other.getTravelDistance());
      }
      if (other.getBuriedness() != 0) {
        setBuriedness(other.getBuriedness());
      }
      if (other.getDamage() != 0) {
        setDamage(other.getDamage());
      }
      if (other.getHP() != 0) {
        setHP(other.getHP());
      }
      if (other.getStamina() != 0) {
        setStamina(other.getStamina());
      }
      if (other.getDirection() != 0) {
        setDirection(other.getDirection());
      }
      if (other.getWater() != 0) {
        setWater(other.getWater());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      adf.sample.tactics.HumanProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (adf.sample.tactics.HumanProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object uRN_ = "";
    /**
     * <code>string uRN = 1;</code>
     * @return The uRN.
     */
    public java.lang.String getURN() {
      java.lang.Object ref = uRN_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uRN_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string uRN = 1;</code>
     * @return The bytes for uRN.
     */
    public com.google.protobuf.ByteString
        getURNBytes() {
      java.lang.Object ref = uRN_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uRN_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string uRN = 1;</code>
     * @param value The uRN to set.
     * @return This builder for chaining.
     */
    public Builder setURN(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uRN_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string uRN = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearURN() {
      
      uRN_ = getDefaultInstance().getURN();
      onChanged();
      return this;
    }
    /**
     * <code>string uRN = 1;</code>
     * @param value The bytes for uRN to set.
     * @return This builder for chaining.
     */
    public Builder setURNBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      uRN_ = value;
      onChanged();
      return this;
    }

    private int iD_ ;
    /**
     * <code>int32 iD = 2;</code>
     * @return The iD.
     */
    public int getID() {
      return iD_;
    }
    /**
     * <code>int32 iD = 2;</code>
     * @param value The iD to set.
     * @return This builder for chaining.
     */
    public Builder setID(int value) {
      
      iD_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 iD = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearID() {
      
      iD_ = 0;
      onChanged();
      return this;
    }

    private int x_ ;
    /**
     * <code>int32 x = 3;</code>
     * @return The x.
     */
    public int getX() {
      return x_;
    }
    /**
     * <code>int32 x = 3;</code>
     * @param value The x to set.
     * @return This builder for chaining.
     */
    public Builder setX(int value) {
      
      x_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 x = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearX() {
      
      x_ = 0;
      onChanged();
      return this;
    }

    private int y_ ;
    /**
     * <code>int32 y = 4;</code>
     * @return The y.
     */
    public int getY() {
      return y_;
    }
    /**
     * <code>int32 y = 4;</code>
     * @param value The y to set.
     * @return This builder for chaining.
     */
    public Builder setY(int value) {
      
      y_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 y = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearY() {
      
      y_ = 0;
      onChanged();
      return this;
    }

    private int positionID_ ;
    /**
     * <code>int32 positionID = 5;</code>
     * @return The positionID.
     */
    public int getPositionID() {
      return positionID_;
    }
    /**
     * <code>int32 positionID = 5;</code>
     * @param value The positionID to set.
     * @return This builder for chaining.
     */
    public Builder setPositionID(int value) {
      
      positionID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 positionID = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPositionID() {
      
      positionID_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList positionHistory_ = emptyIntList();
    private void ensurePositionHistoryIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        positionHistory_ = mutableCopy(positionHistory_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int32 positionHistory = 6;</code>
     * @return A list containing the positionHistory.
     */
    public java.util.List<java.lang.Integer>
        getPositionHistoryList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(positionHistory_) : positionHistory_;
    }
    /**
     * <code>repeated int32 positionHistory = 6;</code>
     * @return The count of positionHistory.
     */
    public int getPositionHistoryCount() {
      return positionHistory_.size();
    }
    /**
     * <code>repeated int32 positionHistory = 6;</code>
     * @param index The index of the element to return.
     * @return The positionHistory at the given index.
     */
    public int getPositionHistory(int index) {
      return positionHistory_.getInt(index);
    }
    /**
     * <code>repeated int32 positionHistory = 6;</code>
     * @param index The index to set the value at.
     * @param value The positionHistory to set.
     * @return This builder for chaining.
     */
    public Builder setPositionHistory(
        int index, int value) {
      ensurePositionHistoryIsMutable();
      positionHistory_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 positionHistory = 6;</code>
     * @param value The positionHistory to add.
     * @return This builder for chaining.
     */
    public Builder addPositionHistory(int value) {
      ensurePositionHistoryIsMutable();
      positionHistory_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 positionHistory = 6;</code>
     * @param values The positionHistory to add.
     * @return This builder for chaining.
     */
    public Builder addAllPositionHistory(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensurePositionHistoryIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, positionHistory_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 positionHistory = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPositionHistory() {
      positionHistory_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private int travelDistance_ ;
    /**
     * <code>int32 travelDistance = 7;</code>
     * @return The travelDistance.
     */
    public int getTravelDistance() {
      return travelDistance_;
    }
    /**
     * <code>int32 travelDistance = 7;</code>
     * @param value The travelDistance to set.
     * @return This builder for chaining.
     */
    public Builder setTravelDistance(int value) {
      
      travelDistance_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 travelDistance = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTravelDistance() {
      
      travelDistance_ = 0;
      onChanged();
      return this;
    }

    private int buriedness_ ;
    /**
     * <code>int32 buriedness = 8;</code>
     * @return The buriedness.
     */
    public int getBuriedness() {
      return buriedness_;
    }
    /**
     * <code>int32 buriedness = 8;</code>
     * @param value The buriedness to set.
     * @return This builder for chaining.
     */
    public Builder setBuriedness(int value) {
      
      buriedness_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 buriedness = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearBuriedness() {
      
      buriedness_ = 0;
      onChanged();
      return this;
    }

    private int damage_ ;
    /**
     * <code>int32 damage = 9;</code>
     * @return The damage.
     */
    public int getDamage() {
      return damage_;
    }
    /**
     * <code>int32 damage = 9;</code>
     * @param value The damage to set.
     * @return This builder for chaining.
     */
    public Builder setDamage(int value) {
      
      damage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 damage = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearDamage() {
      
      damage_ = 0;
      onChanged();
      return this;
    }

    private int hP_ ;
    /**
     * <code>int32 hP = 10;</code>
     * @return The hP.
     */
    public int getHP() {
      return hP_;
    }
    /**
     * <code>int32 hP = 10;</code>
     * @param value The hP to set.
     * @return This builder for chaining.
     */
    public Builder setHP(int value) {
      
      hP_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 hP = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearHP() {
      
      hP_ = 0;
      onChanged();
      return this;
    }

    private int stamina_ ;
    /**
     * <code>int32 stamina = 11;</code>
     * @return The stamina.
     */
    public int getStamina() {
      return stamina_;
    }
    /**
     * <code>int32 stamina = 11;</code>
     * @param value The stamina to set.
     * @return This builder for chaining.
     */
    public Builder setStamina(int value) {
      
      stamina_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 stamina = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearStamina() {
      
      stamina_ = 0;
      onChanged();
      return this;
    }

    private int direction_ ;
    /**
     * <code>int32 direction = 12;</code>
     * @return The direction.
     */
    public int getDirection() {
      return direction_;
    }
    /**
     * <code>int32 direction = 12;</code>
     * @param value The direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirection(int value) {
      
      direction_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 direction = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearDirection() {
      
      direction_ = 0;
      onChanged();
      return this;
    }

    private int water_ ;
    /**
     * <code>int32 water = 13;</code>
     * @return The water.
     */
    public int getWater() {
      return water_;
    }
    /**
     * <code>int32 water = 13;</code>
     * @param value The water to set.
     * @return This builder for chaining.
     */
    public Builder setWater(int value) {
      
      water_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 water = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearWater() {
      
      water_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:simpleRCRS.HumanProto)
  }

  // @@protoc_insertion_point(class_scope:simpleRCRS.HumanProto)
  private static final adf.sample.tactics.HumanProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new adf.sample.tactics.HumanProto();
  }

  public static adf.sample.tactics.HumanProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HumanProto>
      PARSER = new com.google.protobuf.AbstractParser<HumanProto>() {
    @java.lang.Override
    public HumanProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HumanProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HumanProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HumanProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public adf.sample.tactics.HumanProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

