// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: firebrigade.proto

package adf.sample.tactics;

public interface WorldInfoProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:simpleRCRS.WorldInfoProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
   */
  java.util.List<adf.sample.tactics.AreaProto> 
      getAreasList();
  /**
   * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
   */
  adf.sample.tactics.AreaProto getAreas(int index);
  /**
   * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
   */
  int getAreasCount();
  /**
   * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
   */
  java.util.List<? extends adf.sample.tactics.AreaProtoOrBuilder> 
      getAreasOrBuilderList();
  /**
   * <code>repeated .simpleRCRS.AreaProto areas = 1;</code>
   */
  adf.sample.tactics.AreaProtoOrBuilder getAreasOrBuilder(
      int index);

  /**
   * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
   */
  java.util.List<adf.sample.tactics.HumanProto> 
      getHumansList();
  /**
   * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
   */
  adf.sample.tactics.HumanProto getHumans(int index);
  /**
   * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
   */
  int getHumansCount();
  /**
   * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
   */
  java.util.List<? extends adf.sample.tactics.HumanProtoOrBuilder> 
      getHumansOrBuilderList();
  /**
   * <code>repeated .simpleRCRS.HumanProto humans = 2;</code>
   */
  adf.sample.tactics.HumanProtoOrBuilder getHumansOrBuilder(
      int index);

  /**
   * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
   */
  java.util.List<adf.sample.tactics.BlockadeProto> 
      getBlockadesList();
  /**
   * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
   */
  adf.sample.tactics.BlockadeProto getBlockades(int index);
  /**
   * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
   */
  int getBlockadesCount();
  /**
   * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
   */
  java.util.List<? extends adf.sample.tactics.BlockadeProtoOrBuilder> 
      getBlockadesOrBuilderList();
  /**
   * <code>repeated .simpleRCRS.BlockadeProto blockades = 3;</code>
   */
  adf.sample.tactics.BlockadeProtoOrBuilder getBlockadesOrBuilder(
      int index);

  /**
   * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
   */
  java.util.List<adf.sample.tactics.ElseProto> 
      getElsesList();
  /**
   * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
   */
  adf.sample.tactics.ElseProto getElses(int index);
  /**
   * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
   */
  int getElsesCount();
  /**
   * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
   */
  java.util.List<? extends adf.sample.tactics.ElseProtoOrBuilder> 
      getElsesOrBuilderList();
  /**
   * <code>repeated .simpleRCRS.ElseProto elses = 4;</code>
   */
  adf.sample.tactics.ElseProtoOrBuilder getElsesOrBuilder(
      int index);

  /**
   * <code>int32 time = 5;</code>
   * @return The time.
   */
  int getTime();
}
